mapeditor/tiled

- translations/tiled_cs.ts
New translations for a new release!
> Update Czech translation

- translations/tiled_fr.ts
Hexagonal maps FTW!
Have a nice Week-End and a nice release. :)
> French translation update for the next Tiled version! :D

- translations/tiled_fr.ts
> Finished the French translation update.

- src/terraingenerator/main.cpp
```
Usage: terraingenerator [options]
Options:
-h --help        : Display this help.
-v --version     : Display the version.
--overwrite   : Target is overwritten rather than extended.
-e --embed-image : Tile images will be embedded in the TSX file instead
of being saved as a separated PNG file.
-c --combine T1[ T2 [Tn ...]]
: Specify the terrains to combine together (all combinations).
-s --source TS1[ TS2 [TSn ...]]
: Add source tilesets, order is not important.
-o --output OUT  : Specify output tileset filename.
-p --priority T1[ T2 [Tn ...]]
: Add terrain names to priority list (T1 < T2 < Tn).
```
Example usage:
```
terraingenerator -o test.tsx --priority LavaRock Dirt2 Dirt Sand Water Hole Grass PlowedSoil Lava --source LavaRock.tsx Dirt2.tsx Dirt.tsx Water.tsx Hole.tsx Grass.tsx …
```
> Added commandline configuration to terraingenerator

- src/tiled/commandlineparser.cpp
- src/tiled/commandlineparser.h
- src/tiled/main.cpp
Implemented 'TODO'. Made cmd line parser translatable.
> Implemented 'TODO'. Made cmd line parser translatable.

- src/tiled/main.cpp
- src/tiled/mainwindow.h
- src/tiled/preferences.cpp
- src/tiled/preferences.h
- src/tiled/preferencesdialog.cpp
- src/tiled/preferencesdialog.h
- src/tiled/preferencesdialog.ui
Now on every opening user will be asked for opening last files. It gives him the choice to open them or not.
> TODO solved. Opening last files is now is optional.

- dist/win/README.txt
- src/tiled/automapper.cpp
- src/tiled/automapper.h
- src/tiled/automapperwrapper.cpp
- src/tiled/automappingmanager.h
- src/tiled/changeimagelayerposition.h
- src/tiled/command.cpp
- src/tiled/commanddatamodel.cpp
- src/tiled/createobjecttool.cpp
- src/tiled/geometry.cpp
- src/tiled/mainwindow.cpp
- src/tiled/mainwindow.h
- src/tiled/stampbrush.h
- src/tiled/utils.h
This pull request contains some cosmetic changes for code: fixed typos (mostly), comments...
> Some code cosmetic changes.

- src/tiled/magicwandtool.h
Fixed comment on magic wand tool.
> Fixed comment on magic wand tool.

- src/tiled/mapsdock.cpp
FIXME solved. Now dragging of directories in the maps dock is disabled in correctly way via creating a new model derived from 'QFileSystemModel' and reimplementing its 'flags(...)'.
> FIXME solved. Refactored disabling of dragging directories in the maps dock.

- .travis.yml
> Let travis build with g++ 4.8

- translations/tiled_cs.ts
Here are new translations for 0.13!
> Update Czech translations

- src/tiled/objectselectiontool.cpp
This solves #1016 and #981 issues
> Avoid Inf values in scaling factors

- util/java/libtiled-java/src/tiled/core/MapObject.java
- util/java/libtiled-java/src/tiled/core/ObjectGroup.java
- util/java/libtiled-java/src/tiled/io/TMXMapReader.java
- util/java/libtiled-java/src/tiled/io/xml/XMLWriter.java
I changed the object's positions and dimensions from ints to floats. I ran the unit tests and they passed.
> Parse objects with floating point positions and dimensions

- translations/tiled_fr.ts
> Updated fr translation + Removed remaining shortcuts translations.

- translations/tiled_de.ts
I created this pullrequest for him since he is apparently struggling with the git tools :)
> Updated German translation

- translations/tiled_fr.ts
Happy New Year! :)
I hope you're going fine. All the best for 2016! :D
> French translation update for 0.15.

- src/automappingconverter/automappingconverter.pro
- src/plugins/plugin.pri
- src/terraingenerator/terraingenerator.pro
- src/tiled/tiled.pro
- src/tmxrasterizer/tmxrasterizer.pro
- src/tmxviewer/tmxviewer.pro
- tests/mapreader/mapreader.pro
- tests/staggeredrenderer/staggeredrenderer.pro
"-z" flag is unsupported on cygwin
> cygwin build workaround

- translations/tiled_de.ts
> Updated the german translation

- translations/tiled_fr.ts
> Updated French translation for Latest Tiled version.

- translations/tiled_tr.ts
Just updated Turkish translations with minor fixes/replacements and new translations.
> Turkish translations updated.

- dist/copr/build.sh
- dist/copr/tiled.spec
The script needs to be invoked with a copr api token as the parameters.
After merging, can you push this to the snapshot branch too please? Then I can do final testing
> Added scripts for building fedora dailies

- src/tiled/tilesetview.cpp
- src/tiled/tilesetview.h
Based on implementation from MapView, with @bjorn as part of the "Spend One Hour Remotely Pair-Programming With Me on Tiled" reward!
Closes #1050
> Add support for scrolling in tileset view with middle mouse button

- translations/tiled_tr.ts
Just updated new entries.
Thanks for keep working.
> Update: Turkish translations.

- translations/tiled_ru.ts
All new strings were translated.
> Updated Russian translation.

- src/tiled/mainwindow.cpp
- src/tiled/mainwindow.ui
- src/tiled/preferences.cpp
- src/tiled/preferences.h
- src/tiled/snaphelper.cpp
- src/tiled/snaphelper.h
Tried to implement #1329 . @bjorn I'm waiting for your critics/notes. These are my notes about this PR:
- Don't sure if I correctly modified SnapHelper::toggleSnap(). Give some advices how it should work by the logic please if I done it wrong.
- Should I also update all *.ts and include them into this commit?
> Implemented 'Snap to pixels'.

- src/tiled/propertiesdock.cpp
- src/tiled/propertiesdock.h
- src/tiled/propertybrowser.cpp
This actually does not changes the type, but deletes and adds the property
> Changing property type context menu #1304

- tiled.appdata.xml
> Added keywords to the appdata file

- docs/map.xsd
It's a beginning towards an updated format. Many things in the XSD depends on the how you use it inside Tiled, which is ambigious in the TMX format page.
> Updated schema to follow the TMX format page

- util/java/libtiled-java/src/main/java/tiled/core/Map.java
- util/java/libtiled-java/src/main/java/tiled/io/TMXMapReader.java
- util/java/libtiled-java/src/main/java/tiled/io/TMXMapWriter.java
- util/java/libtiled-java/src/test/java/tiled/io/MapReaderTest.java
- util/java/libtiled-java/src/test/resources/tiled/io/resources/hexagonal.tmx
- util/java/libtiled-java/src/test/resources/tiled/io/resources/staggered.tmx
- util/java/tmxviewer-java/src/main/java/TMXViewer.java
Fixed shifted / staggered issue and added stagger axis, stagger index and hex side length properties to fix issue  #1237
> fix libtiled-java shifted / staggered issue

- docs/reference/support-for-tmx-maps.md
> add link to tmxlite C++ parser

- src/libtiled/mapobject.cpp
- src/libtiled/mapobject.h
- src/tiled/flipmapobjects.cpp
- src/tiled/flipmapobjects.h
- src/tiled/propertybrowser.cpp
Implemented feature requested in #1475. Now group of objects flipping like expected
> Added flipping a group of objects like expected

- src/tiled/mainwindow.cpp
- src/tiled/mainwindow.h
- src/tiled/mainwindow.ui
Addresses #563. Added private slot to MainWindow which does all the work, appropriate QAction and modified View Menu to accommodate new option.
> Added auto-show/hide all palettes (Clear View) option to View menu

- src/plugins/tbin/tbinplugin.cpp
> Fix .tbin exporting tile properties.

- docs/reference/support-for-tmx-maps.md
Added RPG Maker MV into Support Tiled documentation
> Added RPG Maker MV into support document

- src/tiled/editpolygontool.h
- src/tiled/mapeditor.cpp
- src/tiled/mapeditor.h
> Delete key deletes selected nodes

- src/tiled/commanddialog.cpp
I guess I missed this one :man_facepalming:
> Disable browse button when select <new command>

- src/tiled/commandmanager.cpp
- src/tiled/commandmanager.h
- src/tiled/mainwindow.cpp
> Add retranslateUi() to CommandManager

- src/libtiled/mapobject.h
- src/libtiled/object.h
- src/tiled/abstractobjecttool.cpp
- src/tiled/abstractobjecttool.h
- src/tiled/changemapobject.cpp
- src/tiled/changemapobject.h
Added a context menu item to reset template instances.
> Enable resetting template instances

- src/tiled/abstracttilefilltool.cpp
- src/tiled/abstracttilefilltool.h
- src/tiled/bucketfilltool.cpp
- src/tiled/bucketfilltool.h
- src/tiled/capturestamphelper.cpp
- src/tiled/capturestamphelper.h
- src/tiled/mapeditor.cpp
- src/tiled/shapefilltool.cpp
- src/tiled/stampbrush.cpp
- src/tiled/stampbrush.h
- src/tiled/tiled.pro
- src/tiled/tiled.qbs
- src/tiled/tilestamp.cpp
@Bdtrotte Is this something you'd be interested in reviewing?
> Fill tool tweaks

- docs/reference/support-for-tmx-maps.rst
Didn't suggest this before as I thought it was just for TMX.
> Add dtiled to libraries doc section.

- src/tiled/mainwindow.ui
- src/tiled/mapview.cpp
- src/tiled/preferences.cpp
- src/tiled/preferences.h
- src/tiled/preferencesdialog.cpp
- src/tiled/preferencesdialog.ui
I have received your advice and I changed the code.
I am glad I learn about the code style needed.
Meanwhile, I have made my proposal and I sent it through Google Summer of Code site.
I am waiting for your feedback!
> Changes to Wheel Zoom Option

- docs/manual/export.rst
> Added docs for running Tiled --export-map headless

- src/tiled/objecttypeseditor.cpp
- src/tiled/objecttypesmodel.cpp
- src/tiled/objecttypesmodel.h
- src/tiled/preferences.cpp
This is my attempt at fixing https://github.com/bjorn/tiled/issues/1679, please let me know if it can be done in a better way!
> Sort object types alphabetically

- util/java/libtiled-java/src/main/java/org/mapeditor/core/MapLayer.java
- util/java/libtiled-java/src/main/java/org/mapeditor/core/ObjectGroup.java
- util/java/libtiled-java/src/main/java/org/mapeditor/core/Properties.java
- util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapReader.java
- util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapWriter.java
- util/java/libtiled-java/src/main/resources/bindings.xjb
I tried to solve a few bugs I was having with this code. There might still be other bugs out there.
> Fix a few bugs in libtiled-java port.

- util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapReader.java
- util/java/libtiled-java/src/main/java/org/mapeditor/view/IsometricRenderer.java
- util/java/libtiled-java/src/main/java/org/mapeditor/view/OrthogonalRenderer.java
Fix for orthogonal and isometric view.
> Tileset offset and Layer offset now considered when drawing with libtiled-java

- README.md
Reworded the README.md file for clarity and concision. All original information was maintained.
> Updated README.md for clarity and concision

- docs/manual/automapping.rst
Fixing the grammar in the first two paragraphs.
> Fix grammar in documentation

- src/tiledquickplugin/tilelayeritem.cpp
- src/tiledquickplugin/tilesnode.cpp
- src/tiledquickplugin/tilesnode.h
> tiledquickplugin: render horizontally and vertically flipped tiles

- translations/tiled_zh.ts
I have translated `tiled_zh.ts`, hope it can be useful.
> translate tiled_zh.ts

- util/java/libtiled-java/src/main/java/org/mapeditor/core/TileLayer.java
Rather than printing a message to STDOUT and doing nothing, it would be much better if this method would instead throw an exception on illegal input.
> Throw an exception here

- README.md
Nitpicky, but just in case nobody else got to it yet. ^^
> Remove an unmatched closing brace in README

- src/plugins/python/pythonbind.cpp
- src/plugins/python/tiledbinding.py
> Add Tile.type() and MapObject.effectiveType() to Python API

- docs/reference/tmx-map-format.rst
Clarify the center of rotation for objects
Also adds a note about rotation for tile-objects.
> Clarify object rotation

- src/tmxrasterizer/tmxrasterizer.cpp
also do not abort rendering if not all tmx files inside a world can be loaded
> add objectgroup rendering to tmxrasterizer

- .github/workflows/ubuntu-latest.yml
This is a test of GitHub Actions, where I'm trying to use it to compile Tiled on the latest version of Ubuntu.
> Compile using GitHub Actions

- docs/reference/json-map-format.rst
I had to look this up else where when I was dynamically creating maps in the fly for phaser, so I thought id add it.
> added some note on how firstgid works

- src/tiled/scriptmanager.cpp
- src/tiled/scriptmanager.h
Added method to auto check whether the script file is UTF-8 encoded.
> Added utf-8 encoding support for script file

- src/libtiled/imagelayer.cpp
- src/libtiled/imagelayer.h
- src/libtiled/mapreader.cpp
Image layer images used separate code, so they didn't support the same
features (like embedding). Follow-up on #2706
> Combine imagelayer and tileset image tags

- src/libtiled/imagelayer.cpp
> Fix issue where images cannot be loaded from Qt resource files

- src/tiled/editablemanager.cpp
- src/tiled/editablemapobject.cpp
> Fix bug in MapObject.layer

- .github/workflows/macos-latest.yml
I don't believe this works yet, but let's have another try to see what was going wrong.
> Set up macOS build on GitHub Actions

- docs/reference/json-map-format.rst
The custom properties had their type and value swapped.
> Fix JSON map example

- src/tiled/filteredit.cpp
- src/tiled/filteredit.h
- src/tiled/locatorwidget.cpp
- src/tiled/locatorwidget.h
- src/tiled/mainwindow.cpp
- src/tiled/mainwindow.h
- src/tiled/mainwindow.ui
- src/tiled/projectdock.cpp
- src/tiled/projectdock.h
- src/tiled/projectmodel.cpp
- src/tiled/projectmodel.h
- src/tiled/rangeset.h
- src/tiled/tiled.pro
- src/tiled/tiled.qbs
- src/tiled/utils.cpp
- src/tiled/utils.h
This adds a new "Open File in Project" action in the "File" menu, which opens a file filter popup that allows you to quickly open any file in the current project.
A few improvements remain to be done. Here's how it looks currently:
> Added a quick way to open a file in the project

- docs/reference/support-for-tmx-maps.rst
(To be fully transparent, they're both mine.)
> Mentioned two additional Java libraries in support-for-tmx-maps.rst

- docs/reference/support-for-tmx-maps.rst
https://github.com/RandyGaul/cute_headers
https://github.com/RandyGaul/cute_headers/blob/master/cute_tiled.h
> added cute tiled to supported frameworks doc

- docs/reference/support-for-tmx-maps.rst
Updated Orx tutorial link since moved in the Orx Wiki.
> Update support-for-tmx-maps.rst for Orx

- .gitignore
- docs/scripting-doc/README.md
- docs/scripting-doc/generate-scripting-tsdoc.sh
- docs/scripting-doc/index.d.ts
- docs/scripting-doc/package-lock.json
- docs/scripting-doc/package.json
The scripting-interface.ts is currently mostly in the state as provided
by Alula on Discord, I only fixed the syntax for some function
declarations so that they pass as regulat .ts files and added
documentation for `registerMapFormat` as a proof of concept.
> Add first draft of tsdoc based documentation

- translations/tiled_zh_CN.ts
fix some translation for better understand
- line 1352, in menu/message, new -> 新建，instead of 创建
- line 906， In menu, world -> 世界，instead of 地图
- line 4126,  add missing translation
- line 4177,  add missing translation
> Update chinese translation tiled_zh_CN.ts

- src/tiledquick/tiledquick.qbs
... by setting the BUILD_TILEDQUICK env var to true.
> Allow building tiledquick by default

- src/tiledquick/qml/main.qml
Please merge as individual commits.
> Add Fit Map in View action/menu item

- docs/scripting-doc/index.d.ts
switched between classes and interfaces multiple times, not 100% how to handle the enums and probably did some errors... But I wanted to dump my current state
> WIP: move documentation to index.d.ts

- src/tiled/mapitem.cpp
- src/tiled/preferences.cpp
- src/tiled/preferences.h
- src/tiled/preferencesdialog.cpp
- src/tiled/preferencesdialog.ui
> Updated Files to Allow for Modification of Background Fade Color (#2862)

- docs/scripting-doc/index.d.ts
refined TiledObject, MapObject, TileMap
added Font, TileLayer, TileLayerEdit, Tileset, Tile
added declarton of WangSet, color, SelectedArea
I tested my added declarations by using them in another project that needs them.
Change-Id: Ice5a64696293de467abc064b16e0096c7224c825
> Added a bunch of definitions, still not all. But I was missing these.

- docs/scripting-doc/index.d.ts
List of changes in this file:
- refine Menu item type
- fix BinaryFile interface
- untangle tileToPixel definitons
- add a few any types to allow compilition in strict mode
- add process class
I use this file in my project https://github.com/MrMasterplan/rwklevelfiles and can report that I can transpile with these changes.
> Cleanup for strict, some fixes, Process class.

- src/tiled/propertiesdock.cpp
Fix flickering the menu when adding/removing components.
> Fix flickering when adding/removing components.

- docs/scripting-doc/index.d.ts
- src/libtiled/object.cpp
- src/libtiled/object.h
- src/libtiled/properties.cpp
- src/tiled/changecomponents.cpp
- src/tiled/changecomponents.h
- src/tiled/document.cpp
- src/tiled/editableobject.cpp
- src/tiled/editableobject.h
- src/tiled/propertiesdock.cpp
- tests/object/object.qbs
- tests/object/test_object.cpp
- tests/tests.qbs
* Add scripting support for components
e.g. tiled.activeAsset.currentLayer.objects[1].addComponent('boss', { hp: 77 })
* addComponent, removeComponent, changeComponentProperty
* Add object `commonComponents` tests
> Add scripting support for components

- src/tiled/mainwindow.cpp
- src/tiled/mapdocumentactionhandler.cpp
- src/tiled/mapdocumentactionhandler.h
Related to issue #3080, a feature I requested.  This adds a menu item with keyboard shortcut for selecting all layers.  I'm not a QT developer, so any comments and pointers will be happily accepted.  Thanks for making Tiled.
> Adds a menu item with keyboard shortcut for selecting all layers.

- docs/reference/support-for-tmx-maps.rst
Some links have changed for these projects recently so just a quick update to them in the docs.
> docs: Update pytiled-parser and Arcade links

- docs/reference/support-for-tmx-maps.rst
Reference: https://excaliburjs.com/docs/tilemap#tiled-plugin
> Add Excalibur HTML5 engine to the list

- docs/scripting-doc/index.d.ts
FileInfo also need to be changed to a namespace.
Related: #3346
> docs: Changed FileInfo script API to a namespace so it can be accessed in TypeScript 

- NEWS.md
- docs/manual/using-commands.rst
- src/tiled/command.cpp
I know that this is basically nothing, but in the game that I'm working on, this would make it way easier to make levels and worlds, so I decided to try to add it.
Basically this is just like the %mapfile variable, but for the tiled worlds
> %worldfile as variable in command.cpp

- NEWS.md
- src/tiled/mainwindow.cpp
- src/tiled/mainwindow.h
> Fixed restoring of window layout when maximized

- docs/reference/support-for-tmx-maps.rst
This PR updates the reference information for LITIENGINE to match the desired capitalization and change wording slightly.
> Update LITIENGINE information.

- docs/scripting-doc/index.d.ts
Add note about problem with current index signal on Dialog's QComboBox
> add warning about QT 5 index change signal on qtcombobox

- docs/scripting-doc/index.d.ts
Came up via #3537 that this was available but not documented
> Add scripting doc for Dialog.exec()

- NEWS.md
- docs/scripting-doc/index.d.ts
- src/tiled/scriptmodule.cpp
- src/tiled/scriptmodule.h
Convenience function for comparing two versions or checking the current version of Tiled.
> Scripting: Added tiled.versionLessThan

- NEWS.md
- src/libtiled/hexagonalrenderer.cpp
Closes #3583
Marked as draft since the "Stagger Axis: X" case hasn't been fully worked out yet.
> Implemented rendering of major grid lines for staggered / hexagonal maps

- NEWS.md
- docs/scripting-doc/index.d.ts
- src/tiled/libtilededitor.qbs
- src/tiled/scriptbase64.cpp
- src/tiled/scriptbase64.h
- src/tiled/scriptmanager.cpp
- src/tiled/scriptmodule.cpp
- src/tiled/scriptmodule.h
Providing some convenience functions for commonly used compression formats and base64 encoding, mostly useful when implementing file formats.
Closes #3153
> Scripting: Added tiled.compress, tiled.decompress and Base64 encoding/decoding

- NEWS.md
- src/libtiled/tiled.cpp
- src/libtiled/tiled.h
- src/tiledapp/main.cpp
- src/tiledquickplugin/tiledquickplugin.cpp
- src/tmxrasterizer/main.cpp
- src/tmxviewer/main.cpp
- src/tmxviewer/tmxviewer.cpp
> Qt 6: Increased the image allocation limit from 128 MB to 1 GB

- src/tiledapp/tiled.rc.in
- src/tiledapp/tiledapp.qbs
> Qbs: Use the texttemplate module for the tiled.rc file

- NEWS.md
- src/libtiled/hexagonalrenderer.cpp
- src/libtiled/hexagonalrenderer.h
- src/libtiled/isometricrenderer.cpp
- src/libtiled/orthogonalrenderer.cpp
> Fixed grid rendering for odd Hex Side Length values

- .github/workflows/codeql-analysis.yml
* Use Ubuntu 22.04
* Updated the codeql-actions from v1 to v2
* Run it also when its workflow file changes
> GitHub Actions: Updated CodeQL workflow

- NEWS.md
- src/tiled/createobjecttool.cpp
- src/tiled/mapobjectitem.cpp
- src/tiled/objectselectionitem.cpp
This fixes a small error in 570fd8071a2c70766cead8476cdb97607324b1e9.
Closes #3669
> Fixed object preview position with parallax factor on group layer

- docs/reference/support-for-tmx-maps.rst
Here's a [new OCaml library](http://github.com/fishyfriend/tmx) for reading TMX data files.
Thanks,
Jacob
> doc: Mention OCaml tmx library

- docs/requirements.txt
Opening PR to test the result.
> docs: Update to Sphinx 6

- NEWS.md
- src/tmxrasterizer/main.cpp
- src/tmxrasterizer/tmxrasterizer.cpp
- src/tmxrasterizer/tmxrasterizer.h
Hello, I thought it would allow tmxrasterizer to be used more dynamically to offer options to hide/show objects.
Please let me know if this is okay for you. Do I need to edit any translation files / doc files to contribute this?
> Allow to hide and show objects in tmxrasterizer

- src/tmxrasterizer/main.cpp
src/tmxrasterizer/main.cpp has "Specifies a object to omit..." and was changed to "Specifies an object to omit..."
> Fix minor typo

- dist/win/installer.wxs
- src/libtiled/libtiled.qbs
> updated qbs file for libtiled to solve naming conflict

- docs/manual/using-infinite-maps.rst
Fixed some typos, reworded some parts for added clarity. Updated alt text to provide improved descriptions for screen reader users.
> Clean up 'Using Infinite Maps' page content for clarity

- .github/workflows/packages.yml
This might eventually help people on Wayland to have working dock widgets.
Issue #3412
> GitHub Actions: Updated to Qt 6.6.1

- .github/workflows/packages.yml
Hopefully this addresses some issues on macOS (see #3876).
> GitHub Actions: Updated to Qt 6.6.2

- NEWS.md
- docs/manual/export-tscn.rst
- src/plugins/tscn/tscnplugin.cpp
> Update Godot 4 exporter to use the new tile rotation/flipping system in Godot 4.2

- NEWS.md
- docs/scripting-doc/index.d.ts
- src/libtiled/properties.h
- src/tiled/fileedit.cpp
- src/tiled/fileedit.h
* Added `FilePath.localFile`
* Added `FileEdit.fileName`
* Added code snippet for converting `QUrl` to a local file path to docs
> Scripting: Added some alternatives to working with URLs

- NEWS.md
- docs/manual/automapping.md
- src/libtiled/tilelayer.h
- src/tiled/automapper.cpp
- src/tiled/automapper.h
- src/tiled/propertybrowser.cpp
- tests/automapping/ignore-flip/map-result.tmx
- tests/automapping/ignore-flip/map.tmx
- tests/automapping/ignore-flip/rules.tmx
- tests/automapping/ignore-flip/rules.txt
- tests/automapping/test_automapping.cpp
> Automapping: Added per-input-layer properties for ignoring flip flags

- dist/install-qt.sh
Nothing really relevant for Tiled, apart from the mirror removal. Just keeping the differences with upstream smaller.
> Updates to install-qt.sh merged from Qbs repository

- src/plugins/python/pythonplugin.cpp
Pressed merge a little too early...
> Python plugin: Added forgotten PyConfig_Clear call

- .editorconfig
[EditorConfig](https://editorconfig.org) is a [well established](https://github.com/search?q=path%3A**%2F.editorconfig&type=code) file format standard and text editor plugins collection that helps contributor keep a consistent coding style. This pull request shares the one I've been using when working on Tiled. Not much more to add, this is just nice to have.
> EditorConfig file

- docs/locale/fr/LC_MESSAGES/manual.po
- docs/locale/fr/LC_MESSAGES/reference.po
- docs/locale/ru/LC_MESSAGES/manual.po
- translations/tiled_bg.ts
- translations/tiled_cs.ts
- translations/tiled_pt.ts
Thank you @firstmiddlelast, @EddieMattos, @lyubomirv, @auzkok and @SantosSi for the updates!
Note that this is a preparation for the string freeze for Tiled 1.11, so there will be more to update soon. :-)
> Merging translation updates from Weblate

- .github/dependabot.yml
Check for updates to GitHub Actions every week.
> GitHub Actions: Check for updates to actions

- NEWS.md
- src/libtiled/libtiled.qbs
- src/libtiled/tmxmapformat.cpp
- src/libtiled/tmxmapformat.h
- src/tiled/libtilededitor.qbs
- src/tmxrasterizer/main.cpp
- src/tmxrasterizer/tmxrasterizer.qbs
- src/tmxviewer/main.cpp
Enabled template resolution for the tmxrasterizer application.
This then provides that image objects are properly rendered if they stem from a template
> Enabled template resolution for the tmxrasterizer application.

- docs/scripting-doc/index.d.ts
Also did some rewrapping and fixed a few parameters to be marked as optional.
> docs: Added link from tiled.prompt to the Dialog API

- docs/scripting-doc/CHANGELOG.md
- docs/scripting-doc/package-lock.json
- docs/scripting-doc/package.json
> docs: Bumped tiled-api to 1.11.0

- docs/manual/terrain.rst
> docs: Improved alt text for transitions-to-empty image

- docs/scripting-doc/index.d.ts
Also, my editor decided to reformat the entire file, but it looks nice and consistent so I'll go with it.
> docs: Added link from World to tiled.worlds

- appveyor.yml
Qt 6.7 is no longer available on AppVeyor.
> AppVeyor: Updated builds to Qt 6.8

- src/libtiled/properties.h
- src/plugins/yy/yyplugin.cpp
- tests/properties/test_properties.cpp
We no longer need to support this ancient version.
> Dropped workarounds for mingw49

- src/tiled/propertieswidget.cpp
Last minute cleanup cleaned up a little too much. We need the list of values, because they don't match the indexes in the names list...
> Fixed changing blend mode in Properties view

- src/tiled/newmapdialog.cpp
This line was just testing the use of a QSize variable in the session.
> Removed leftover test variable from session

- util/java/libtiled-java/pom.xml
- util/java/pom.xml
- util/java/tmxviewer-java/pom.xml
* Specify `requireMavenVersion` 3.5.4
* Update all plugins accordingly
* Update dependencies to their latest releases
* Use `maven.compiler.release` instead of source/target
* Updated http URLs to https
> libtiled-java: Various pom.xml updates
