mapeditor/tiled

util/java/libtiled-java/src/tiled/core/MapObject.java, util/java/libtiled-java/src/tiled/io/TMXMapReader.java
TMXMapReader looks for the "gid" attribute when reading map objects. If it finds one it gives the MapObject a reference to the relevant Tile. If the gid value can't be parsed to an integer it will crash.
=> Added a Tile reference for MapObjects

src/libtiled/libtiled.qbs
libtiled uses QPixmap in its headers, which requires that any project
that uses libtiled also depends on Qt Gui.
This makes the qbs file more reusable for 3rd party programs/libraries.
=> Added Qt.gui to Export{} of libtiled.qbs

src/libtiled/hexagonalrenderer.cpp, src/libtiled/isometricrenderer.cpp, src/libtiled/mapreader.cpp, src/libtiled/maprenderer.cpp, src/libtiled/maprenderer.h, src/libtiled/orthogonalrenderer.cpp, src/tiled/createobjecttool.cpp, src/tiled/mapobjectitem.cpp, src/tiled/mapobjectitem.h, src/tiled/objectselectiontool.cpp, src/tiled/objectselectiontool.h
Depends on pull requests #591 and #592, so you might want to get through them first to make the comparison less unsightly. Replaces pull #485. Does the following:
- Map renderer supports scaling of cells.
- Map reader and object tile creation will initialize the size of the object to the tile's size.
- Removed handles from mapobjectitem.cpp.
- In objectselectiontool.cpp, added a set of 8 ResizeHandles, and changed the Corner enum to AnchorPosition, representing the edge centers as well.
- When a single object is selected, resizing is handled in object space.
- When multiple objects are selected, resizing is handled in world space.
Caveats:
- Negative scaling factors are not allowed.
=> Map Object resizing, v3!

src/libtiled/mapwriterinterface.h, src/plugins/csv/csvplugin.cpp, src/plugins/csv/csvplugin.h, src/tiled/mainwindow.cpp
- Layers get exported in different files.
- Filenames are constructed as
#base_#layer.csv
where #base is the name chosen in the
save-file dialog (without extension), and
#layer is the name for the layer.
Related to #277
=> Extend CSV plugin to export all tile layers.

src/libtiled/logginginterface.h, src/libtiled/mapreader.h
There are some classes which used as base for other classes and haven't got virtual destructors. It could be the reason of memory leaks in some cases. This pull request fixes this situation.
=> Fixed possible memory leaks.

src/tiled/propertiesdock.cpp
This patch selects next property when user deletes one.
=> TODO solved. Select next property after deleting one.

src/tiled/propertybrowser.cpp, src/tiled/propertybrowser.h
Property browser improved to be translated immediately. Property browser is updated when some object (different from current one) is set. So it's not good to modify setObject(...) and then call it. I decided to use LanguageChange event and split up setObject(...)'s content into some funcs which used shared by setObject(...) and retranslateUi(...). This patch was created to fix #992.
=> Bugfix for #992 Property browser improved to be translated immediately.

dist/win/dist.qbs, dist/win/tiled.nsi, src/plugins/python/python.qbs, tiled.qbs
You can now build the NSIS installer using `qbs -p dist` or `qbs --all-products`
It will not be built during a default invocation of Qbs (think `make dist` vs `make`/`make all`)
=> Build fixes

src/tiled/mapdocumentactionhandler.cpp
Fortunately, I found time to look into #1005. Not sure is it a correct fix. In updateActions() at the moment of deleting mapDocument still returns 2 layers (when should be one), so the guaranteed deletion would be after layerRemoved signal as I think.
=> Fixed issue #1005.

src/tiled/propertybrowser.cpp, src/tiled/propertybrowser.h
Pull request for #997 
Added four read-only properties:
1. Source Image;
2. Tile Size;
3. Margin;
4. Spacing;
These properties are added only if the tileset isn't the type of 'Collection of images'.
=> Added new read-only properties for tilesets.

src/tiled/mainwindow.cpp, src/tiled/mainwindow.h, src/tiled/mainwindow.ui
Useful feature to save all opened documents at once. Useful when game developer opens all his game's levels in an editor then edit them in similar way and wants to save them with one click.
=> Added 'File => Save All' functionality.

appveyor.yml
Another small improvement to CI config. I'm working on getting Qbs available through Chocolatey as well so then you'll be able to easily use a newer version without relying on Qt Creator.
=> AppVeyor: install NSIS using the Chocolatey package manager.

util/java/libtiled-java/src/tiled/io/TMXMapWriter.java
Fixes saving maps that have tilesets with duplicate names.
=> Use tileset as the key in the map used to look up firstgids.

src/tiled/randompicker.h
I'm developing [a game](https://youtu.be/mrLlPNSvDJ0) with my friend, that includes random level generator. The level generator works better, if I set terraintypes to as many tiles as possible. However, I don't want these tiles to appear when modifying terrain in Tiled, so I set their probability to zero. This causes problems, because things in QMap container in RandomPicker get overwritten.
In this pull request, I've modifier the RandomPicker class, so it ignores those things that have zero probability or less. It fixes the problem.
I tested it with stamp and bucket fill with random mode, and I also tested terrain tool. It didn't cause any problems, not even when I set everything to have zero or negative probability.
=> RandomPicker no longer accepts things that have probability zero or less

README.md
=> Building on debian requires libqt5opengl5-dev.

src/libtiled/isometricrenderer.cpp
Removes a previous issue where the render logic rounded odd tile heights.
Closes #85
=> Fix isometric rendering bug

README.md
Since Tiled requires QT to be above version 5, you need to install qt5
with homebrew, not qt (which is version 4). Also since qt5 is keg-only,
it must be linked with the --force flag to be added to the path.
=> Update OSX install instructions for QT

src/tiled/objecttypes.cpp, src/tiled/objecttypes.h, src/tiled/preferences.cpp, src/tiled/preferences.h, src/tiled/preferencesdialog.cpp, src/tiled/preferencesdialog.h, src/tiled/propertybrowser.cpp
Related to the following issues, maybe even more: #365 #392 #367
Allows loading of objecttypes with default properties from xml.
Test-data: [objecttypes.xml for Stendhal entities](http://arianne.cvs.sourceforge.net/viewvc/arianne/stendhal/tiled/objecttypes.xml?content-type=text%2Fplain) by @nhnb
=> Loading Objecttypes.xml with default properties

src/tiled/tiled.pro
I have a resource compilation error when tried to build Tiled on Windows 7 with MinGW (Qt 5.4.2) with qmake. The error occured because of wrong resource filename in *.pro file. In *.qbs file name is written correctly. After this fix 'Tiled' was built OK.
=> Fixed compilation on Windows with MinGW and qmake.

src/tiled/propertybrowser.cpp
Found a bug: If you select multiple tiles, and try to add a new property to them, the editor segfaults. This does not happen if you select the tile with lowest ID last.
I think the reason is, that mObject doesn't have the property (yet?), since the value.type() will be 0. When I selected the lowest ID tile last, the value.type() was 10 and there was no segfault.
When you then call mVariantManager->addProperty(value.type(), name); and value.type() is 0, then it returns property that is NULL, and things start going wrong.
I made a little fix, but I have to admit that **I have no idea if this is the correct way to fix this**. Anyway, it seems to work with tiles now. I also tested with map properties and I also played with undo/redo and I didn't found any problems after this fix.
=> Prevent segfault when adding new property to many tiles.

docs/reference/support-for-tmx-maps.md
Quite a few people are using MonoGame.Extended for Tiled map loading and rendering. It has support for almost every feature in the editor and works on most MonoGame supported platforms out of the box.
=> Added MonoGame.Extended as one of the C# loaders

src/tiled/changetileprobability.cpp, src/tiled/changetileprobability.h, src/tiled/propertybrowser.cpp
I tested undo and redo and they seem to work.
There is one case that doesn't work:
1. Have tiles with probabilities 0, 0, 0, 1.
2. Select them from first to last, so that last selected has probability 1.
3. Now try to set probability to 1 for all of them and nothing happens.
The reason is, that the whole changing event is not triggered, since the value of the last tile wasn't really changed (1 changes to 1).
=> It is now possible to set probability of multiple tiles.

util/java/libtiled-java/src/tiled/io/TMXMapReader.java
When the map is not square, the tiles will be disordered because of the wrong index. fix it by changing it from `ml.getHeight()` to `ml.getWidth() `
=> correct the index of csvTileIds

src/tiled/mainwindow.cpp, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h, src/tiled/mapdocumentactionhandler.cpp, src/tiled/preferences.cpp, src/tiled/preferences.h, src/tiled/resizedialog.cpp, src/tiled/resizedialog.h, src/tiled/resizedialog.ui
Code for #1032 Added option in resize dialog to decide whether invisible objects (which are outside of map) should be deleted from the map. The option is stored/loaded to/from settings.
=> Added option for removing invisible objects in resize dialog.

dist/copr/tiled.spec
I apparently pushed a build with a version number of 9999 while testing
tito. So I need to bump epoch in order to allow a clean upgrade path.
No need to merge to the snapshot branch. I triggered a manual build.
=> Bumped epoch of tiled.spec

src/tiled/command.cpp
Useful for team projects where map and/or script locations differ
=> Replace %mappath with absolute path to map file's directory

util/java/libtiled-java/pom.xml, util/java/pom.xml, util/java/tmxviewer-java/dependency-reduced-pom.xml, util/java/tmxviewer-java/pom.xml
A few changes to Maven POMs have needed to be done to allow artefacts to be deployed to OSSRH snapshots repository, they can now be accessed from:
https://oss.sonatype.org/content/repositories/snapshots/org/mapeditor/
=> Allow Java artefacts to be deployed to OSSRH

util/java/libtiled-java/src/main/java/tiled/core/ObjectGroup.java, util/java/libtiled-java/src/test/resources/tiled/io/resources/csvmap.tmx, util/java/libtiled-java/src/test/resources/tiled/io/resources/sewers.tmx
Update test tmx files to v0.17.0 format and add color to ObjectGroup to suppress unsupported attribute warning when loading map to fix issue #124
=> Suppress unsupported attribute warnings in libtiled-java

src/plugins/gmx/gmxplugin.cpp
Hey @bjorn and @JonesBlunt,
Thanks for making this plugin.
Not sure if it was intended or not, to not include margin and spacing, so I added few code lines to support that.
Also fixed tile->tileset()->tileWidth() to tile->tileset()->tileHeight() for yo attribute.
=> Tileset margin and spacing for gmx plugin

util/java/libtiled-java/src/main/java/tiled/view/IsometricRenderer.java, util/java/tmxviewer-java/src/main/java/TMXViewer.java
created a basic isometric map renderer to libtiled-java, it is able to load isometric maps such as isometric_grass_and_water.tmx in TMX Viewer e.g:
=> Add a basic isometric renderer to libtiled-java

appveyor.yml, dist/distribute.qbs, qbs/imports/TiledPlugin.qbs, qbs/imports/TiledQtGuiApplication.qbs, src/automappingconverter/automappingconverter.qbs, src/libtiled/libtiled.qbs, src/tiled/tiled.qbs, tiled.qbs, translations/translations.qbs
This raises the minimumQbsVersion to 1.5.2. In Qbs 1.5.2, osx was
renamed to macos. This is a forward compatible change, as Qbs guarantees
that macos is in the targetOS list if osx is.
=> Fix macOS build

src/tiled/mainwindow.cpp, src/tiled/mapdocumentactionhandler.cpp, src/tiled/mapdocumentactionhandler.h
To fix this issue:
https://github.com/bjorn/tiled/issues/1423
=> Invert Selection

src/libtiled/mapformat.h, src/plugins/csv/csvplugin.cpp, src/plugins/csv/csvplugin.h, src/plugins/defold/defoldplugin.cpp, src/plugins/defold/defoldplugin.h, src/plugins/droidcraft/droidcraftplugin.cpp, src/plugins/droidcraft/droidcraftplugin.h, src/plugins/flare/flareplugin.cpp, src/plugins/flare/flareplugin.h, src/plugins/gmx/gmxplugin.cpp, src/plugins/gmx/gmxplugin.h, src/plugins/json/jsonplugin.cpp, src/plugins/json/jsonplugin.h, src/plugins/lua/luaplugin.cpp, src/plugins/lua/luaplugin.h, src/plugins/python/pythonplugin.cpp, src/plugins/python/pythonplugin.h, src/plugins/python/scripts/mappy.py, src/plugins/python/scripts/pk2.py, src/plugins/python/scripts/zst.py, src/plugins/replicaisland/replicaislandplugin.cpp, src/plugins/replicaisland/replicaislandplugin.h, src/plugins/tengine/tengineplugin.cpp, src/plugins/tengine/tengineplugin.h, src/plugins/tmw/tmwplugin.cpp, src/plugins/tmw/tmwplugin.h, src/tiled/main.cpp, src/tiled/tmxmapformat.h
For Issue #1382 
Added a new virtual method to MapFormat called `shortName` to use whenever a short descriptive name is needed. Particularly for CLI input/output.
Added short names for all map format plugins.
`--export-formats` now uses the `shortName()`
`--export-map` now uses the `shortName()`
`--export-map` with no filter argument still uses `nameFilter()`
I've used the names of the modules as reference, if any of them are not appropriate I will change them.
=> Issue #1382: Added short and consistent map format names to use with --export-map

src/libtiled/mapobject.h, src/tiled/propertybrowser.cpp
Fix for #1451. Disables WidthProperty and HeightProperty for Polygon and Polyline objects.
=> Disable width and height for Polygon and Polyline objects.

src/tiled/mapdocument.cpp, src/tiled/mapscene.cpp, src/tiled/objectsdock.cpp
I added little usability improvement from #1424. Now when selecting object not from current layer, the layer with selected object will become active.
I'm not sure should I write my code as static function or private method.
=> Change current layer depending on selected objects, usability issue #1424

src/tiled/tileseteditor.cpp
This pull request closes https://github.com/bjorn/tiled/issues/1227 
When adding an image to a Tileset, it checks if the image already exists in the collection and warn the user if so.
The approach was: try to match for each added image, its image source with the images already in the collection (O(n^2))
=> Check for duplicates when adding tiles

src/tiled/commandbutton.cpp, src/tiled/commandbutton.h, src/tiled/commanddatamodel.cpp, src/tiled/commanddatamodel.h, src/tiled/commanddialog.cpp, src/tiled/commanddialog.h, src/tiled/commanddialog.ui, src/tiled/commandmanager.cpp, src/tiled/commandmanager.h, src/tiled/mainwindow.cpp, src/tiled/mainwindow.h, src/tiled/mainwindow.ui, src/tiled/tiled.pro, src/tiled/tiled.qbs
This fixes #943. I previously made a PR, but it lacked a lot of features. Here's a basic gist of what I've done now:
- Created a menu just for Commands
- Contains an action to `Edit Commands`
- Contains a list of all the enabled commands. Also has a shortcut for the first enabled command. This list gets refreshed each time the menu is opened. This is to ensure that the command list is updated and the disabled/enabled commands are updated.
Here's a screenshot of the same:
I made a `CommandManager` class which is instantiated once in `MainWindow`. This manages the menu (updates the commands) and the signals/slots for them.
=> Option to run commands from Menu as well as edit them - Fixes #943

src/tiled/commandbutton.cpp, src/tiled/commanddialog.cpp, src/tiled/commanddialog.h, src/tiled/commanddialog.ui, src/tiled/commandmanager.cpp, src/tiled/commandmanager.h, src/tiled/mainwindow.cpp
This is the follow-up patch for #1463. I've also modified the code on the basis of comments mentioned by @bjorn in the same pull request.
I've added a function `registerMenu(QMenu *menu)` which adds `menu` to the list of all menus that the singleton `CommandManger` has stored in `QList<QMenu*> mMenus`. Another function `updateActions` is added, which deletes all the previously created `QAction` instances and updates the list on the basis of `CommandDataModel`. The slot `populateMenu` will just add all the `QAction` instances present in `mActions` to all the registered `QMenu`.
I've also fixed a small bug: whenever the `Edit Commands...` dialog is prompted, and the list is updated, the effect is not visible until the user opens a particular menu (the menus and the commands get updated only …
=> Same QAction to all QMenu. Follow up patch for #1463

.gitignore
I ran the command `qmake` and then `make` inside the tests directory and it resulted in two untracked files. As far as I know, these two files should be in `.gitignore`.
I don't know if my assumption is true though. Please have a look!
=> Added Executable files in tests directory to gitignore

src/tiled/mapobjectmodel.cpp, src/tiled/mapobjectmodel.h, src/tiled/objectsdock.cpp, src/tiled/objectsdock.h, src/tiled/objectselectiontool.cpp
Implemented feature requested in #1462. Now objects view has switchable id, x, y columns. Columns can be switched by calling context menu on objects view header.
=> Added switchable columns to objects view

src/tiled/command.cpp, src/tiled/command.h, src/tiled/commanddatamodel.cpp, src/tiled/commanddatamodel.h, src/tiled/commanddialog.cpp, src/tiled/commanddialog.h, src/tiled/commanddialog.ui
This fixes #942 
Firstly, I've modified the layout of the Command Dialog. Also, I've made the option "Save Map before Execute" unique to each command. The user can now either enter the command, or he can browse an executable.
=> Added an executable picker - Fixes #942

src/libtiled/map.h, src/tiled/stampbrush.cpp, src/tiled/stampbrush.h
Previously when using the stamp brush tool when in hexagonal mode, moving down rows would cause a stamp to behave strangely (not accounting for the stagger). This has been patched over by shifting every other row of the stamp over in the appropriate direction when needed.
This is my first contribution, and major edit of tiled, so feedback on how anything could be done better would be greatly appreciated!
Ben
=> Stamp brush now works with the stagger in hex mode as expected

src/tiled/objectselectionitem.cpp
Used a QTimer to repeatedly redraw the marquee, upon every redraw, A solid white line is drawn then black dashes are drawn above it shifted by the offset to simulate the marching ants effect.
Currently when selecting 100 objects simultaneously there was a slight increase in CPU usage to about 7-8%.
Redraws happen every 100ms, and offset increases by one, this numbers were chosen arbitrarily to look ok, but needs feedback.
Here is how it looks:
=> Implemented marching ants effect on selected objects(#1489)

src/tiled/mapdocument.cpp
Objects were not offseted if the "Remove objects outside of the map" was not set
=> Fixed objects offsetting while resizing

.mailmap, src/tiled/automapper.cpp
see #1224 for an explanation.
It has been a long time of no tiled programming. It took me a while to remember the details as well as getting it to build (I still had qt4 configured ...)
=> Automapping fix #1224

src/tiled/objectselectionitem.cpp
Used a custom dash line and flat cap to make the black and white dashes have the exact same length, also fixed a typo in the comment.
The chosen length is 5 pixels, but other lengths like 4 or 6 pixels also look fine.
=> Adjusted dash length in object selection rectangle

src/tiledquick/main.cpp, src/tiledquick/qml.qrc, src/tiledquick/tiledquick.pro
This avoids the need to mess around with import paths for the
application's QML files.
=> Add qml.qrc for tiledquick's QML files

src/tiled/mapdocument.cpp, src/tiled/minimap.cpp, src/tiled/minimap.h, src/tiled/minimaprenderer.cpp, src/tiled/minimaprenderer.h, src/tiled/resizehelper.cpp, src/tiled/resizehelper.h, src/tiled/tiled.pro, src/tiled/tiled.qbs
I think it is useful to allow a user to see what exactly is going to be removed while resizing and visually estimate the proportions.
- Rendering of a minimap is now located in a singleton, which can be accessed from both an editor and a resizing window. Maybe it is not a perfect architecture solution, but at lest it works. Waiting for a feedback regarding it.
- I think now there is no reason to scale the preview when the old rect goes outside the view, so a user can see a more detailed picture of a map.
=> Minimap in a resizing dialog

src/tiledquickplugin/tiledquickplugin.pro
Applications that want to use quicktiledplugin will be expecting
the qmldir to be with all of the other plugin-related files.
=> Copy qmldir for in-source builds as well

src/tiledquick/main.qml
toFixed() rounds, which we don't want.
=> Floor tile coordinates in status bar

src/tiledquickplugin/mapitem.cpp
This allows QML code to be guaranteed that MapItem has a renderer by
the time onMapChanged is called, which is necessary to be able to
e.g. set a transform using e.g. pixelToScreenCoords().
=> MapItem: emit mapChanged() after calling refresh()

src/tiled/command.cpp, src/tiled/command.h, src/tiled/commanddatamodel.cpp, src/tiled/commanddatamodel.h, src/tiled/commanddialog.cpp, src/tiled/commanddialog.h, src/tiled/commanddialog.ui
This addresses #941. I've also split 'Command' to 'Executable' and 'Arguments'. I've shown the design in the issue and one of the reasons for this was `..the "Browse" button to choose the executable currently resets the command line arguments.`
A screenshot of what I've done:
=> Allow setting working directory

src/tiled/command.cpp, src/tiled/command.h, src/tiled/commanddatamodel.cpp, src/tiled/commanddatamodel.h, src/tiled/commanddialog.cpp, src/tiled/commanddialog.h, src/tiled/commanddialog.ui, src/tiled/commandmanager.cpp, src/tiled/commandmanager.h, src/tiled/consoledock.cpp
This closes #1552. I've attached a screenshot of the same.
=> Show output of commands in Debug Console

src/plugins/gmx/gmxplugin.cpp, src/plugins/gmx/gmxplugin.h
Okay this adds the ability to define views in game maker by creating an object in tiled.
Set it to the size you want your view. Make sure x,y,width,height, etc are all Ints because thats what GM uses. Numbers will be rounded but that could lead to unexpected results.
If this looks good i can add some better docs and maybe some screen shots
Basically create an object set type to "view"
properties can be defined on the object the match gms properties like so:
Views must be enabled in the map properties since this config comes before views are defined unless you can think of a better way of auto detecting them. I didn't want to iterate through the layers again just to find out if the views were defined. But we could?
Map Properties:
=> Added support for defining gm views with objects

util/java/libtiled-java/src/main/java/tiled/core/TileSet.java
Issue #1626 happens because an incorrect exception is caught in TileSet#getTile(). This makes it catch the correct exception.
=> Fixed wrong exception being caught in TileSet.

src/libtiled/tileset.h, src/tiled/documentmanager.cpp, src/tiled/documentmanager.h, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h, src/tiled/terrainbrush.cpp, src/tiled/terraindock.cpp, src/tiled/terraindock.h, src/tiled/terrainmodel.cpp, src/tiled/terrainmodel.h, src/tiled/tiled.pro, src/tiled/tiled.qbs, src/tiled/tilesetdock.cpp, src/tiled/tilesetdock.h, src/tiled/tilesetdocument.cpp, src/tiled/tilesetdocument.h, src/tiled/tilesetdocumentsmodel.cpp, src/tiled/tilesetdocumentsmodel.h
This model lists the tileset documents that are currently open, and the sort-filter version sorts them by name and filters out tilesets that are embedded in other maps than the current one.
This model extracts part of the logic from TilesetDock, so that it could be reused by an updated TerrainModel. The TerrainModel currently only lists terrains from tilesets that are already part of the map, but it should display all loaded external tilesets.
This is for addressing the following issue raised on the forum:
http://discourse.mapeditor.org/t/created-a-terrain-but-its-not-showing-up-in-the-terrain-tab/2478
=> Introduced TilesetDocumentsModel and its sort-filter model companion

src/libtiled/tiled.h, src/libtiled/tilelayer.cpp, src/libtiled/tilelayer.h, src/tiled/bucketfilltool.cpp, src/tiled/tilesetdock.cpp
In progress PR for #260.
Currently I've added a class `Block` which is a 16x16 grid of cells. This is used in `TileLayer` and now, TileLayer no longes needs `mGrid`, and only stores instances of `Block`. The blocks are stored in a `QMap` and these blocks get deleted when they're empty.
=> Supporting Infinite Maps

src/plugins/plugins.qbs, src/plugins/tbin/plugin.json, src/plugins/tbin/tbin.pro, src/plugins/tbin/tbin.qbs, src/plugins/tbin/tbin/FakeSfml.hpp, src/plugins/tbin/tbin/Layer.hpp, src/plugins/tbin/tbin/Map.cpp, src/plugins/tbin/tbin/Map.hpp, src/plugins/tbin/tbin/PropertyValue.hpp, src/plugins/tbin/tbin/Tile.hpp, src/plugins/tbin/tbin/TileSheet.hpp, src/plugins/tbin/tbin_global.h, src/plugins/tbin/tbinplugin.cpp, src/plugins/tbin/tbinplugin.h
(#1560)
At the moment, loading is fully implemented (except tilesheet tile properties - they're stored as properties on the tilesheet with tbins, I forgot about that (EDIT: And it looks like individual tile properties are currently stored in the tilesheet?)) besides needing to manually fix tilesheet image sources. (It says it can't find it in '.', do I need to put the full path?)
Next I'm going to do saving, and then take out `FakeSfml.hpp` and fix things to use the primitive types directly, as well as `QPointI` (?) instead of `sf::Vector2i` (plus any other cleanup wanted).
=> Implement .tbin file format

src/tiled/changemapobject.cpp, src/tiled/changemapobject.h, src/tiled/tilesetdock.cpp
When the tile of an object is replaced with a tile from an unused tileset, the new tileset wasn't added to the map. This PR fixes that.
=> Fix tile replacement

src/libtiled/tilelayer.h, src/tiled/bucketfilltool.cpp, src/tiled/tilesetdock.cpp
=> Adds iterator and const_iterator for TileLayer

src/tiled/brushitem.cpp
This gives a clear sign to the user in case of locked layer. Also helps when the current layer is not locked but some parent layer is locked because it's not very intuitive that we won't be able to paint on the current layer.
=> Show red highlight over brush item on locked layer

src/tiled/abstractobjecttool.cpp, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h, src/tiled/newtemplatedialog.cpp, src/tiled/newtemplatedialog.h, src/tiled/newtemplatedialog.ui, src/tiled/objecttemplatemodel.cpp, src/tiled/objecttemplatemodel.h, src/tiled/templatesdock.cpp, src/tiled/templatesdock.h
This PR adds some convenience features to the templates dock and template saving.
=> Templates dock enhancements

src/tiled/mainwindow.ui
There doesn't seem to be a strong standard for which shortcut to use. I
would prefer Ctrl+Shift+S because it's used in Visual Studio and Qt
Creator, and consistent with Ctrl+Shift+W for Close All.
However, Ctrl+Shift+S is already used as Save As on some platforms (e.g.
Gnome), which instead use Ctrl+Shift+L for Save All, so we follow suit.
=> Added keyboard shortcut for Save All, Ctrl+Shift+L

src/libtiled/maptovariantconverter.cpp, src/libtiled/maptovariantconverter.h, src/libtiled/mapwriter.cpp, src/libtiled/templategroupformat.cpp, src/libtiled/templategroupformat.h, src/libtiled/varianttomapconverter.cpp, src/libtiled/varianttomapconverter.h, src/plugins/json/jsonplugin.cpp, src/plugins/json/jsonplugin.h, src/tiled/brokenlinks.cpp, src/tiled/mainwindow.cpp, src/tiled/mainwindow.h, src/tiled/newtemplatedialog.cpp, src/tiled/templategroupdocument.cpp, src/tiled/templategroupdocument.h, src/tiled/templatesdock.cpp, src/tiled/tmxmapformat.cpp, src/tiled/tmxmapformat.h
This PR adds JSON support for the reusable object templates, Tiled should be able to:
The groups file is used internally by Tiled, so I'm not sure if it's necessary to save it in JSON.
=> Add JSON support for reusable object templates

src/tiled/changepolygon.cpp, src/tiled/changepolygon.h, src/tiled/editpolygontool.cpp, src/tiled/editpolygontool.h
If two consecutive nodes are selected, then you can delete the edge between them to convert a polygon to polyline.
=> Adds option to remove an edge from polygon

src/tiled/bucketfilltool.cpp, src/tiled/stampbrush.cpp, src/tiled/wangbrush.cpp, src/tiled/wangfiller.cpp, src/tiled/wangfiller.h, tests/staggeredrenderer/test_staggeredrenderer.cpp
=> WangTiles now supports infinite maps

src/tiled/bucketfilltool.cpp, src/tiled/stampbrush.cpp, src/tiled/wangdock.cpp, src/tiled/wangdock.h, src/tiled/wangfiller.cpp, src/tiled/wangfiller.h
As well as removed the unused `mIsInfinite` from the `WangFiller`
=> Made Wang Pattern and color view into a tab widget

src/libtiled/mapobject.h, src/libtiled/objecttemplate.h, src/tiled/abstractobjecttool.cpp, src/tiled/abstractobjecttool.h, src/tiled/abstracttool.cpp, src/tiled/abstracttool.h, src/tiled/createobjecttool.cpp, src/tiled/createobjecttool.h, src/tiled/createtileobjecttool.cpp, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h, src/tiled/mapeditor.cpp, src/tiled/mapeditor.h, src/tiled/mapview.cpp, src/tiled/mapview.h, src/tiled/objecttemplatemodel.cpp, src/tiled/objecttemplatemodel.h, src/tiled/propertiesdock.cpp, src/tiled/templatesdock.cpp, src/tiled/templatesdock.h, src/tiled/tilesetdock.cpp, src/tiled/tilesetdock.h, src/tiled/tilesetview.cpp, src/tiled/tilesetview.h, src/tiled/toolmanager.cpp, src/tiled/toolmanager.h
This PR is part of the object templates project.
The goal is to be able to edit the templates and reflect those edits in the map.
A new view is embedded into the dock to show the template and allow graphical editing, also the properties can be edited through the properties dock.
=> Editing templates

src/tiled/changepolygon.cpp, src/tiled/changepolygon.h, src/tiled/editpolygontool.cpp
If two consecutive nodes are selected in a polyline and then the segment between them can be deleted to split polyline into two polylines.
=> Option to split polyline

src/libtiled/tilelayer.cpp, src/libtiled/tilelayer.h, src/tiled/automapper.cpp, src/tiled/automapperwrapper.cpp, src/tiled/automappingmanager.cpp
This patch aims to fix the automap issue in infinite-maps.
=> Fix automap

src/libtiled/gidmapper.cpp, src/libtiled/gidmapper.h, src/libtiled/mapreader.cpp, src/libtiled/mapwriter.cpp, src/libtiled/varianttomapconverter.cpp
I've removed `startx` and `starty` attributes from Tile Layer. Now, for infinite maps, each 16x16 chunk will be stored along with its `startx` and `starty` coordinates.
=> New chunk based format for infinite maps

src/libtiled/mapobject.cpp, src/libtiled/mapobject.h, src/libtiled/mapwriter.cpp, src/libtiled/objecttemplate.h, src/tiled/abstractobjecttool.cpp, src/tiled/abstractobjecttool.h, src/tiled/changemapobject.cpp, src/tiled/changemapobject.h, src/tiled/mainwindow.cpp, src/tiled/mainwindow.h, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h, src/tiled/mapdocumentactionhandler.cpp, src/tiled/mapdocumentactionhandler.h, src/tiled/newtemplatedialog.cpp, src/tiled/newtemplatedialog.h, src/tiled/objecttemplatemodel.cpp, src/tiled/objecttemplatemodel.h, src/tiled/propertybrowser.cpp, src/tiled/propertybrowser.h, src/tiled/templatesdock.cpp, src/tiled/templatesdock.h, src/tiled/tmxmapformat.cpp, src/tiled/tmxmapformat.h
This pull request contains various minor improvements to templates
I'm not sure about these two
=> Various improvements for templates

src/plugins/python/pythonbind.cpp, src/plugins/python/scripts/fotf.py, src/plugins/python/scripts/mappy.py, src/plugins/python/scripts/pk2.py, src/plugins/python/scripts/zst.py, src/plugins/python/tiledbinding.py
I added SharedTileset data() method, regenerated pythonbind.cpp (I think, change order of lines in python file caused change of many lines), and fixed scripts for this and other interfaces changes (I tested them all, but don't know, what SNES game used by the author or original plugin - they can have different tiles format, as I know, maybe I write my own plugin for NES format in future, I know it much better).
=> fix python scripts for updated tiled interfaces

src/tiled/documentmanager.cpp, src/tiled/documentmanager.h, src/tiled/mainwindow.cpp
This commit adds "Close", "Close Other Tabs", and "Close Tabs To The
Right" to the document tab context menu. It also adds the ability to
close tabs with middle-click.
=> Improve tab closing functionality (#1720)

src/plugins/flare/flareplugin.cpp
#1417 appears to have been untouched for the passed 9 months or so. I've fixed the merge conflicts, as well as making a few style changes based on how we format data for Flare. The output we want is `background_color=R,G,B,A`, where RGBA are 8-bit integers.
=> Fixed proposed changes to Flare plugin

src/tiled/selectionrectangle.cpp
This change fixes an issue where the shadow of the selection rectangle would drift away from the selection based on the current zoom level (more zoom = more drift). With this change, the shadow is always on pixel away from the selection.
=> Fixed a bug where selection rectangle's shadow moved when zooming

src/tiled/documentmanager.cpp
Proposed fix for https://github.com/bjorn/tiled/issues/1782.
With this change, the save dialog will re-open afters users answer no to the "Tiled may not automatically recognize your file when loading. Are you sure you want to save with this extension?" dialog.
The diff whitespace looks funny on Github for some reason, I'm not too sure why considering it's all spaces (and indented correctly).
=> Reopen save dialog when user heeds file extension warning

src/tiled/documentmanager.cpp
Removes the need to translate untitled.tmx to just translate untitled, that is already used in saving a tsx file.
=> Reduce translatable strings

src/tiled/tilesetdock.cpp, src/tiled/tilesetdock.h
Feature announced in the issue #1766.
=> Add 'New Tileset...' button when no tileset is opened

src/tiled/brokenlinks.cpp, src/tiled/brokenlinks.h, src/tiled/documentmanager.h, src/tiled/mapeditor.cpp, src/tiled/templatesdock.cpp, src/tiled/templatesdock.h
This pull request aims to enable fixing bad links inside templates (#1732).
Tileset bad reference and tileset bad image reference can be fixed from the templates view independent from the map. I provided a button and a label that shows the bad file link to allow fixing things and update the template and consequently the instances.
This works without using BrokenLinks at all, but there is still broken links integration which checks if there is any problem with any template (bad tileset link or image) and allows opening the template in the dock where we can carry on with the fixes.
If a tileset document is already opened then and we open it through the templates dock to fix the image, a new tab is opened for the same tileset document, I think the shared tileset pointers from the opened …
=> Fix broken tileset inside template

src/tiled/editor.h, src/tiled/mainwindow.cpp, src/tiled/mainwindow.h, src/tiled/mapeditor.cpp, src/tiled/mapeditor.h, src/tiled/tileseteditor.cpp, src/tiled/tileseteditor.h
This allows the user to reset the MapEditor's widget layout to default layout setting that tiled comes with, without requiring them to restart the Tiled.
=> Ability to reset MapEditor's layout to default layout without terminating/restarting Tiled

src/libtiled/tileset.cpp
This part should not be reached in theory.
Let's return an empty QString anyways to be on the save side and to make
the compiler happy.
Fixes 'Program returns random data in a function'.
=> Fix return in Tileset::orientationToString

docs/reference/json-map-format.rst, src/libtiled/maptovariantconverter.cpp, src/libtiled/maptovariantconverter.h, src/libtiled/varianttomapconverter.cpp, src/libtiled/varianttomapconverter.h
Addresses issue https://github.com/bjorn/tiled/issues/1585
This introduces a new json revision (version: 1.2) that is much easier to serialize and de-serialize.  For an example of de-serializing the new format in Unity3d, see https://github.com/saeedakhter/TiledJsonUnity3d
**Problem:**
Tiles were serialized as a map with the tile ID as the key:
```
"tiles":
{
"0": { "image":"necro3_0\/5.png", "imageheight":32, "imagewidth":32 },
"1": { "image":"necro3_0\/4.png", "imageheight":32, "imagewidth":32 }
}
```
In Unity3d, this makes it difficult (impossible?) to use Unity3d's JSON deserialization:
https://docs.unity3d.com/Manual/JSONSerialization.html 
**Solution (this pull request):**
Serialize tiles and properties as a list.  If an ID is required, put it inside the list object.  Example:
``` …
```
=> Jsonformat

.gitignore, src/tiled/main.cpp
@bjorn Please review.  Adding an --export-tileset command line arg has been quite useful to me.  Also, please make sure to see the comments at L385.  I believe tileset export was recently broken  (the "Export..." menu item has the same behavior).  Here's a sample tsx to json export to illustrate:
```
{ "source":"mytileset.tsx",
"version":1.2
}
```
=> Add --export-tileset command line argument

.travis.yml, appveyor.yml, dist/win/installer.qbs, dist/win/installer.wxs, qbs/imports/PythonProbe.qbs, src/plugins/python/find_python.pri, src/plugins/python/python.qbs, src/plugins/python/pythonbind.cpp, src/plugins/python/pythonplugin.cpp, src/plugins/python/pythonplugin.h, src/plugins/python/scripts/fotf.py, src/plugins/python/scripts/lib/cpystruct.py, src/plugins/python/scripts/lib/lbm.py, src/plugins/python/scripts/lib/mappy_types.py, src/plugins/python/scripts/lib/utils.py, src/plugins/python/scripts/mappy.py, src/plugins/python/scripts/pk2.py, src/plugins/python/scripts/zst.py, src/plugins/python/tiledbinding.py
Built simply by `qmake . && make` and after `cp -a src/plugin/python/scripts ~/.tiled` at least fotf.py works out of the box (don't have data files to test all the other ones atm).
Noticed the new qbs build files later on. Since osx ships with py2 preinstalled but not with py3 I've changed the build to use pkgconfig for osx as well, which seems to work (after finally figuring out PkgConfigProbe defaulted to qbs.sysroot i.e. /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk for .pc files)
Steps:
-  install [py3.6.4 x64](https://www.python.org/ftp/python/3.6.4/python-3.6.4-amd64.exe), and set the checkbox under advanced options to add it to environment variables (PATH) (there's [some reasons](https://bugs.python.org/issue3561#msg164635) why …
=> python3 support

src/libtiled/imagereference.cpp, src/libtiled/tiled.cpp
While irrelevant for the end users of Tiled as an application, this
allows those of us using Tiled as a library to have maps whose tilesets
are stored in resources.
=> Allow qrc-based tileset images

src/libtiled/tiled.cpp, src/libtiled/tiled.h, src/tiledquickplugin/maploader.cpp, src/tiledquickplugin/tilelayeritem.cpp
A similar change was done a while ago in a1ceb57e, but the code has
changed a lot since then, so it needs to be updated.
=> tiledquick: allow qrc-based tileset images

src/plugins/lua/luaplugin.cpp
`columns` field was not being included.
=> Include columns in lua export

translations/tiled_de.ts
I fixed a small typo in the help section.
User manual != Benutzerhanduch
User manual == Benutzerhand**b**uch
=> Fixed typo in tiled_de.ts

src/plugins/lua/luaplugin.cpp
Properties are copied from the template, then overwritten by the instances's properties before being written to the export.
Pros:
* Backwards compatible with older tools/importers
* No need to check templates for properties
* No extra runtime overhead, compared to not using templates
Cons:
* Can't directly tell if the object had a template
* Can't tell if any properties were from the template or not
=> Add support to Lua exporter for object templates

src/tiled/mainwindow.cpp
This is useful when different files have the same name
=> Display full path in recent files menu

src/tiled/commanddatamodel.cpp
Fixed crash caused by badly calculated argument in beginRemoveRows function call that led to SIGSEGV when attepting to remove command and only one left in list
=> Fixed crash on remove command attempt (#2014)

src/tiled/newsfeed.cpp
Under certain conditions, this seems to be causing a [build failure](https://667000.bugs.gentoo.org/attachment.cgi?id=547810) with qt-5.11.
=> Add missing include.

src/tiled/objectselectionitem.cpp, src/tiled/objectselectionitem.h
Closes #1976.
Adds new slot to `ObjectSelectionItem` that listens for `objectGroupChanged` from `MapDocument` (a signal that is triggered whenever the layer color is changed) and updates color labels when a signal is received.
=> GH1976 Labels change color when layer color is changed

src/tiled/automappingmanager.cpp, src/tiled/automappingmanager.h
closes #1997 
Automatic update of mapping rules whenever rules.txt is changed, and rules are only reloaded when switching maps if the maps are in different directories
=> GH1997 Add QFileSystemWatcher for rules.txt

README.md
Fixes the error `Unknown module(s) in QT: qml`
=> Add qtdeclarative5-dev to dependencies

src/libtiled/tileset.cpp
89aa41b and 9764a01 already made these kind of changes, so this
just fixes it in another place after 9202e25.
=> Allow qrc-based tileset images in new tileset code

src/plugins/python/pythonbind.cpp, src/plugins/python/tiledbinding.py
This pull request adds a method to the Python API, `loadSharedTilesetFromTsx`, which allows loading an existing TSX file as a tileset.
The use case I'm thinking of is embedding the path to a specific version of a TSX in a map format, then attempting to resolve it when the map is loaded in Tiled, and sharing the same TSX across multiple map files. The data system we have may support several groups of tiles loaded from outside sources like mods which can be enabled and disabled, so I was thinking about pregenerating a TSX for a single supported configuration of enabled/disabled mods, caching the tile images somewhere, and allowing them to be used in the editor.
=> Allow loading a TSX file from Python plugins

src/libtiled/worldmanager.cpp, src/libtiled/worldmanager.h, src/tmxrasterizer/main.cpp, src/tmxrasterizer/tmxrasterizer.cpp, src/tmxrasterizer/tmxrasterizer.h
With this PR, users will be able to convert a .world file into a .png file by running the command :
tmxrasterizer <worldFile> <destPngFile> [options...]
This PR does not affect .tmx/.json conversion to png.
=> Add support for .world files in tmxrasterizer

docs/reference/json-map-format.rst
While parsing some of the example files, I noticed this field was in the exported file but not in my parsing. I don't know if it's all that relevant for a non-editor (since it says this is used in by the editor) but since it can be in the file it seems like it should be listed for completeness.
=> Add Tile.probability field in JSON spec

docs/reference/json-map-format.rst
This makes it easier to convert to an enum if generated classes from this spec.
=> Add possible renderorder values to spec

docs/reference/json-map-format.rst
If you reference an external tileset and then save as JSON, there's a `source` field but it's not mentioned in the docs (which means if you code-gen from the spec, you don't have it :-)).
I didn't copy the whole description of this from the XML spec as it'd get a bit messy in this table, but it miht be easier to do that if this file changes to using the CSV format.
=> Add "source" field for Tileset object

docs/reference/json-map-format.rst
When re-generating after changing to CSVs, I noticed this property moved from ImageLayer down to Layer. I think this was unintended that this should be marked as imagelayer *only*.
=> Add missing "only" to JSON spec

docs/reference/tmx-map-format.rst
There are three uses of staggered tiles: Staggered Isometric, Staggered Hexagonal, and Staggered Orthogonal (which is normal squares, but each tile has 6 neighbors instead of 9). So the name `staggered` could refer to either the Isometric or the Orthogonal meanings (hexagonal is clearly documented as using staggered axes in addition to the `staggered` orientation).
=> Clarify the meaning of the "staggered" orientation

src/libtiled/object.h, src/plugins/python/pythonbind.cpp, src/plugins/python/tiledbinding.py
Adds `Object.propertyType()` to the Python API. This way plugin code can properly encode the types of properties without having to guess what they are using `Object.propertyAsString()`.
=> Allow retrieving the type of a property from Python

src/tiled/tileanimationeditor.cpp
On HiDPI displays preview box tile animation is very small.
This patch adds zooming to scale defined for animation editor popup.
=> Animation preview follows zoom factor for tiles

src/tiled/automapper.cpp, src/tiled/automapper.h
I decided to edit Tiled's source code after viewing [this discussion about the behavior of automapping near the map's edges](https://discourse.mapeditor.org/t/automapper-ignore-the-empty-void-beyond-the-perimeter-of-map/) and I was not satified with the state of the art of automapping near the borders.
Normally, when you try to automap near the edges, the edges are seen as empty tiles, failing to apply, for example, Remex's auto-generated rules (the ones originated from RPG Maker):
This pull request add two options (as map properties) to customize the behavior of automapping near the edges.
- **OverflowBorder**: this option makes the automapper treats the out-of-bounds areas of the map as if they were prolongations of the border tiles, thus applying the rules along the borders as if they …
=> Add options to customize "MatchOutsideMap" behavior

docs/manual/automapping.rst
This pull request add the features `OverflowBorder` and `WrapBorder` mentioned in #2141 to the automapping documentation. It should look like this:
=> Change documentation to reflect the addition of new features

src/tiled/abstracttiletool.cpp, src/tiled/editablelayer.cpp, src/tiled/editablemap.cpp, src/tiled/layerdock.cpp, src/tiled/layerdock.h, src/tiled/layermodel.cpp, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h, src/tiled/mapdocumentactionhandler.cpp, src/tiled/mapeditor.cpp, src/tiled/mapeditor.h, src/tiled/mapitem.cpp, src/tiled/objectsview.cpp, src/tiled/reparentlayers.cpp, src/tiled/templatesdock.cpp, src/tiled/tilecollisiondock.cpp, src/tiled/tilesetdock.cpp, src/tiled/tilesetdock.h
I was working on #2065 and I added a method `setCurrentLayerByName` to `MapDocument` so that after `DocumentEditor` switches documents within a world, it can try to also change the layer to one with an identical name, as the original issue requested.
I was not able to reproduce the second request in the original issue. Changing the active tileset already persists between maps for me.
=> Try to keep layer by name in worlds (#2065)

src/libtiled/filesystemwatcher.cpp
It appears that when this bug  ( https://github.com/bjorn/tiled/issues/44 ) happens, the watcher starts handling the filesystem change before the file actually gets recreated. So the new version of the file doesn't exist, and never gets added back to the watcher.
This PR moves the functionality of re-adding the file to the watcher into the timeout handler. In my tests, this gives it enough time for the file to exist again, and thus gets re-added.
I'm not well-versed in QT, so if I should be handling the iteration with a different type of Iterator, or use a different style here, please let me know.
=> Possibly fixes issue #44 -- Improves how file system watcher handles replaced files 

src/tiled/document.cpp, src/tiled/document.h, src/tiled/documentmanager.cpp, src/tiled/mapdocument.cpp, src/tiled/tilesetdocument.cpp
=> use QHash instead of QList for Document::sDocumentInstances

util/java/libtiled-java/src/main/java/org/mapeditor/core/Tile.java, util/java/libtiled-java/src/main/java/org/mapeditor/core/TileLayer.java, util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapReader.java, util/java/libtiled-java/src/test/java/org/mapeditor/io/MapReaderTest.java, util/java/libtiled-java/src/test/resources/flipped/flipped.tmx
Hello hello. We have met some problems while trying to use libtiled in our project: reading of flipped tiles and reading of images. Here is our solution(we also added a test for flipped tiles).
=> Libtiled tile read fix

appveyor.yml, src/libtiled/libtiled.qbs
For some reason, cpp.staticLibraries also looks for dynamic libraries. Made it so that the dynamic library does not get build on windows, so it cannot be linked. Turns out that there's no need to differentiate between platforms anymore.
=> Link zstd static library instead of dynamic library on windows

.travis.yml
=> Travis CI: Compile only the static libzstd.a for macOS

docs/reference/tmx-map-format.rst
This is noted in the section for <point>, but <object> was missing this as a possibility.
=> Add note that <object> can have <point> as a child

docs/reference/tmx-map-format.rst
Explain in detail how fonts are laid out in the object. Also note in the documentation that fonts are clipped outside of the bounds of their object.
These details were determined from how Tiled handles text objects.
For a quick explanation of font terminology, see this image: https://i.stack.imgur.com/ntg5f.png
=> Add technical details for font display

docs/reference/tmx-map-format.rst
It wasn't clear from the documentation whether the `name` and `type` fields of `object` tags could be safely omitted from TMX files. Giving them a default value makes clear that they can be left out.
=> Specify defaults for name and type

src/plugins/defoldcollection/defoldcollection.pro, src/plugins/defoldcollection/defoldcollection.qbs, src/plugins/defoldcollection/defoldcollectionplugin.cpp, src/plugins/defoldcollection/defoldcollectionplugin.h, src/plugins/defoldcollection/defoldcollectionplugin_global.h, src/plugins/defoldcollection/plugin.json, src/plugins/plugins.pro, src/plugins/plugins.qbs
This pull request adds a plugin to Tiled, which allows exporting a map into a .collection (Defold's prefab).
Exporting into a collection allows the use of:
- Group layers (**only top-level group layers are supported, not nested ones!**)
- Multiple Tilesets per Tilemap
Upon export:
- The **Path** property of each Tileset may need to be set up manually in Defold after each export. However, Tiled will attempt to find the .tilesource file corresponding with the name of the Tileset in Tiled in your project's /tilesources/ directory. If one is found, manual adjustments won't be necessary. The way Tiled finds the root of your project is by looking for a file called "game.project" while going up the hierarchy, starting from the directory where you save the collection. Therefore, if you save your …
=> Added export to Defold .collection files

src/libtiled/logginginterface.h, src/libtiled/tileset.cpp, src/libtiled/wangset.cpp, src/tiled/changepolygon.h, src/tiled/commanddatamodel.cpp, src/tiled/tiledproxystyle.cpp
- src/libtiled/tileset.cpp:517:19: warning: 'swap' is deprecated: Use QList<T>::swapItemsAt() [-Wdeprecated-declarations]
- src/libtiled/wangset.cpp:596:5: warning: 'qStableSort<QList<Tiled::WangTile>::iterator>' is deprecated: Use std::stable_sort [-Wdeprecated-declarations]
- src/libtiled/logginginterface.h:51:1: warning: 'Issue' defined as a struct here but previously declared as a class [-Wmismatched-tags]
- src/tiled/commanddatamodel.cpp:489:19: warning: 'swap' is deprecated: Use QList<T>::swapItemsAt() [-Wdeprecated-declarations]
- src/tiled/changepolygon.h:100:9: warning: private field 'mObjectIndex' is not used [-Wunused-private-field]
- src/tiled/tiledproxystyle.cpp:126:24: warning: 'find' is deprecated: Use bool find(const QString &, QPixmap *) instead …
=> Fix build warnings on macOS with Qt 5.13.1

src/tiled/issuescounter.cpp
With `tr("%1...", "", n)`, Qt looks for two markers in the translation: `%1` for the argument and `%n` to select the right plural.
Qt Linguist flags translations that don't have `%n` and `%1`.
But, it makes sense to only have the number once in the translation.
=> issuescounter.cpp: Use %n for plural translations

src/tiled/preferencesdialog.ui
If the translation is long, it would stretch the dialog.
This makes the label the same size as the accelerated rendering one.
=> Preferences dialog: Stretch the wheelZoomsByDefault checkbox label

src/tiled/objecttypeseditor.cpp, src/tiled/objecttypeseditor.h, src/tiled/preferences.cpp, src/tiled/preferences.h
related to issue #1816 
I added a FileSystemWatcher to Preferences to watch the objecttypes.xml for changes.  When the file changes, it calls setObjectTypes() which emits the objectTypesChanged.
I also had to modify the ObjectTypesEditor to listen for the Preferences::objectTypesChanged signal so it will also update for external changes.
=> auto-reload object types file when changed externally

util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapWriter.java
This code *should* work, but I'm unable to compile & test it with my
setup. I don't understand how jaxb is setup. The main possible failure
is if the .getTile() function isn't actually generated by jaxb.
Closes #2128 if merged.
=> Attempt to fix java tile type bug

docs/reference/tmx-map-format.rst
All "can contain" entries have been split into "can contain at most one"
and "can contain any number". Additionally, there is now a note to
implementors at the top of the specification listing how to handle parsing
errors. (More of a reminder on how to handle XML errors in general, since
TMX is a form of XML.)
Closes #696, #1754
=> Clarify "can contain" documentation and error handling

src/libtiled/mapreader.cpp, src/tiled/mapview.cpp
While trying to tackle #920, I had issues loading my test files. So I found these performance improvements in the CSV decoder and the first render of the map.
I wasn't able to make any more progress in 920, so this PR is just the speedups I found on the way.
=> Map loading speedups

docs/reference/tmx-map-format.rst
All optional attributes are now marked as optional. All attributes have
a default value, if applicable. A new line was added at the top of the
docs to clearly state that all optional and default fields are correctly
marked. Made the default value wording consistent throughout all
attributes.
Additionally, I documented previously undocumented behavior in wangtile,
and updated the supported encodings to include "zstd".
Followup on #2702, improving #696 solution.
=> Document all optional attributes, update some docs

docs/reference/scripting.rst
It's faster to find the objects in the side bar when they're ordered
alphabetically. I wanted to also sort functions and properties, but they
have a consistent ordering, and it wouldn't speed up lookups by much.
=> Alphabetize scripting API reference

src/tiled/mapview.cpp
Previously, loading a large map initialized the zoom to arbitrarily small
scales. During my testing, a 3000x3000 map would load in at 0.06% zoom.
Rendering all those tiles made the first draw and any user actions,
including zooming back in, very very slow.
This commit caps the number of tiles on screen to about 4,000 for the first
draw. The user is still free to zoom out, but the app will start out much
more responsive.
Split off from #2701
=> Speed up first-draw by reducing initial map size

src/tiled/consoledock.cpp, src/tiled/consoledock.h, src/tiled/scriptmanager.cpp, src/tiled/scriptmanager.h
Similar to google chrome's debug console. Makes working with intermediate values easier.
=> Assign global variables to console evals

src/libtiled/isometricrenderer.cpp, src/libtiled/layer.cpp, src/libtiled/layer.h, src/libtiled/mapreader.cpp, src/libtiled/maprenderer.cpp, src/libtiled/maprenderer.h, src/libtiled/maptovariantconverter.cpp, src/libtiled/mapwriter.cpp, src/libtiled/orthogonalrenderer.cpp, src/libtiled/varianttomapconverter.cpp, src/plugins/lua/luaplugin.cpp, src/tiled/changeevents.h, src/tiled/changelayer.cpp, src/tiled/changelayer.h, src/tiled/mapitem.cpp, src/tiled/mapitem.h, src/tiled/propertybrowser.cpp, src/tiled/propertybrowser.h, src/tiled/undocommands.h
Initial implementation for tinting a tile layer. the matter of stacking the tint of group layers in the same manner it happens with opacity in the current version of tiled was not handled. Also, tinting non tile layers was also not handled.
Closes #2683
=> Added layer tint color

src/tiled/editablemap.cpp, src/tiled/editableobjectgroup.cpp, src/tiled/editabletile.cpp, src/tiled/mapeditor.cpp, src/tiled/scriptedtool.cpp, src/tiled/scriptfileformatwrappers.cpp, src/tiled/scriptmanager.cpp, src/tiled/scriptmanager.h, src/tiled/scriptmodule.cpp, src/tiled/tilesetdock.cpp
QJSEngine can pass a nullptr to a `Q_INVOKABLE` or `Q_PROPERTY` function if the argument is either `undefined` or the wrong type.
=> Added checks for nullptr in script arguments

src/libtiled/properties.cpp, src/libtiled/properties.h, src/tiled/main.cpp, src/tiled/propertiesdock.cpp, src/tiled/propertybrowser.cpp, src/tiled/variantpropertymanager.cpp
Users could have previously had custom properties of type int that
referenced objects by ID. Registering a converter for ObjectRef to
and from int should help migration to the new object reference type.
Updates #707
=> support converting object reference property to and from int

src/tiled/mainwindow.cpp, src/tiled/mainwindow.ui, src/tiled/objectselectionitem.cpp, src/tiled/objectselectionitem.h, src/tiled/preferences.cpp, src/tiled/preferences.h
Initial work on implementing #707 based on the recently implemented object reference properties. This change is about visualizing the connections between objects.
=> Added visualization of object references

src/libtiled/hexagonalrenderer.cpp, src/libtiled/hexagonalrenderer.h, src/libtiled/isometricrenderer.cpp, src/libtiled/isometricrenderer.h, src/libtiled/maprenderer.h, src/libtiled/orthogonalrenderer.cpp, src/libtiled/orthogonalrenderer.h, src/tiledquick/qml/main.qml, src/tiledquickplugin/mapitem.cpp, src/tiledquickplugin/mapitem.h, src/tiledquickplugin/tilelayeritem.cpp, src/tiledquickplugin/tilelayeritem.h
=> tiledquickplugin: only render visible tiles 

src/libtiled/grouplayer.h, src/libtiled/imagelayer.h, src/libtiled/layer.h, src/libtiled/map.cpp, src/libtiled/map.h, src/libtiled/mapobject.h, src/libtiled/object.h, src/libtiled/objectgroup.h, src/libtiled/objecttemplate.h, src/libtiled/terrain.h, src/libtiled/tile.h, src/libtiled/tilelayer.h, src/libtiled/tileset.h, src/libtiled/wangset.h, src/tiled/editablemap.cpp, src/tiled/editablemap.h, src/tiledquickplugin/mapitem.cpp, src/tiledquickplugin/mapitem.h, src/tiledquickplugin/maploader.h, src/tiledquickplugin/mapref.h, src/tiledquickplugin/tiledquickplugin.pro, src/tiledquickplugin/tiledquickplugin.qbs, src/tiledquickplugin/tilelayeritem.cpp
Deriving from QObject makes them rather more heavy-weight than necessary. The only reason they were derived from QObject was to expose them to QML, but so far this functionality is not actually used. Only Tiled::Map was passed on in QML and this use-case was replaced by a small wrapper.
In general we now have "Editable" wrappers around these base objects, which I'd aim to expose in the TiledQuickPlugin somehow, for use by Tiled Quick.
@mitchcurtis Since you may be relying on these classes, please let me know if this would cause you any headaches.
=> Don't derive base libtiled classes from QObject

src/tiled/tilesetdock.cpp
This makes any workflow involving "picking" tiles from the map much easier.
=> Switch current tileset tab if all selected tiles are from the same tileset

docs/reference/support-for-tmx-maps.rst
Corona SDK was recently rebranded to Solar2D so I've renamed the Corona SDK section of the frameworks list, and moved it to retain alphabetical ordering.
=> Replaced Corona SDK references with Solar2D

src/tiled/mapview.cpp
This is a small fix that prevents a segmentation fault in MapView::fitMapInView() if no scene is assigned to the view.
=> Prevent segfault in MapView::fitMapInView() if no scene is assigned

docs/reference/scripting.rst, src/libtiled/object.cpp, src/libtiled/object.h, src/plugins/gmx/gmxplugin.cpp, src/tiled/editableobject.cpp, src/tiled/editableobject.h, src/tiled/propertiesdock.cpp
Per discussion on https://github.com/bjorn/tiled/issues/2664 , this adds new callbacks to access properties that allow inheritance, rather than shoving inheritance into the existing callbacks. The existing function name Object::inheritedProperty is ambiguous/misleading, so I went with propertyIncludingInherited.
=> Allow scripting API to access properties inherited from templates

NEWS.md, docs/reference/scripting.rst, src/tiled/scriptfileinfo.cpp, src/tiled/scriptfileinfo.h, src/tiled/scriptmanager.cpp, src/tiled/tiled.pro, src/tiled/tiled.qbs
Based on the Qbs FileInfo service.
I've taken the code from https://github.com/4QJS/Qbs4QJS/blob/master/fileinfo.h and adjusted it a little:
* Removed `fromWindowsSeparators` and `toWindowsSeparators` (which were just calling the same function as the "Native" versions of these).
* Returned `absoluteFilePath` for the `absolutePath` function, to make sure the file name is still included.
* Dropped intention to support "hostOS" parameter, which only really makes sense in Qbs as build system.
* Code style changes.
* Documentation reformatted and adjusted.
Co-authored-by: @konsumer
=> Scripting: Added FileInfo API

docs/reference/support-for-tmx-maps.rst
This patch adds Planimeter's Grid engine to the "Support by Framework"
section.
=> Add Planimeter's Grid engine to reference

src/libtiled/tilesetmanager.h, src/tmxrasterizer/main.cpp, src/tmxrasterizer/tmxrasterizer.cpp, src/tmxrasterizer/tmxrasterizer.h
Relates to #1433 .
**Objective**
Allow a user to advance animations by a duration prior to rasterizing an image via tmxrasterizer.
**Reasoning**
This is an alternative to GIF support. A user can script multiple tmxrasterizer commands, each advancing the animation. This results in multiple PNG files, which the user can stitch together with any GIF creation tool such as `imagemagick`.
**Notes**
This should work with worlds, as it includes the tile animation reset. However I have not yet tested it on an animated world.
=> Add animation advancing to tmxrasterizer

appveyor.yml
Also updated version of Qbs used from 1.13.1 to 1.16.0.
=> AppVeyor: Added Qt 5.15 to the build matrix

src/tiled/snaphelper.cpp, src/tiled/snaphelper.h
Well I don't really know if CTRL-SHIFT is a good idea but since CTRL was to toggle snapping to grid, I thought to keep the idea the CTRL 'toggles' snapping, and with SHIFT you switch to fine grid.
Hopefully it makes sense.
=> using CTRL-SHIFT to toggle snapping to fine grid mode

docs/manual/editing-tile-layers.rst, src/tiled/eraser.cpp, src/tiled/eraser.h
To implement shift erase, I had to remove the check for Qt::NoModifier so I don't know if that's gonna collide with another command.
=> Holding shift with the eraser erases from all layers

src/libtiled/hexagonalrenderer.cpp, src/libtiled/hexagonalrenderer.h, src/libtiled/isometricrenderer.cpp, src/libtiled/isometricrenderer.h, src/libtiled/maprenderer.cpp, src/libtiled/maprenderer.h, src/libtiled/orthogonalrenderer.cpp, src/libtiled/orthogonalrenderer.h, src/libtiled/tilelayer.cpp, src/libtiledquick/tilelayeritem.cpp, src/tiled/tilelayeritem.cpp
Continues on from https://github.com/bjorn/tiled/pull/2840.
This allows custom tile-rendering code to benefit from the tile position
calculations that the renderers do. It is necessary in order to allow
each tile to be its own QQuickItem.
Discussion about the motivation for this patch can be found here:
https://discourse.mapeditor.org/t/z-ordering-issues-tiledquickplugin/4546
=> Pass tilePos to RenderTileCallback

util/java/libtiled-java/src/main/java/org/mapeditor/core/MapObject.java, util/java/libtiled-java/src/main/java/org/mapeditor/core/TileLayer.java, util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapReader.java, util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapWriter.java, util/java/libtiled-java/src/main/java/org/mapeditor/io/xml/XMLWriter.java, util/java/libtiled-java/src/main/resources/bindings.xjb, util/java/libtiled-java/src/main/resources/map.dtd, util/java/libtiled-java/src/main/resources/map.xsd, util/java/libtiled-java/src/test/java/org/mapeditor/io/MapReaderTest.java
I've been making modifications to the libtiled-java in order to use it for automated processing/modifying of Tiled maps.
It's very much based on my current needs, so the features added to reading&writing the map files are features I've noticed end up with differences (or missing data altogether) in the map files.
I'm opening this PR mostly in case someone else has a need to touch the map files programmatically while maintaining the same file structure (the goal is to have no changes if you just do read/write with the Java lib).
Hoping to get this clean enough to be mergeable in the future.
=> libtiled-java - Tiled editor parity

.github/workflows/packages.yml, snap/snapcraft.yaml
If this works we'll set up publishing of the snap as well. 
This should eventually help with #2828. Even though the edge channel always has a build of the latest master, it would be good to have actual snapshot builds (maybe on beta channel) and to push tags to release or rc channel.
=> GitHub Actions: Added building of the snap package

docs/reference/scripting.rst, src/tiled/editableimagelayer.cpp, src/tiled/editableimagelayer.h, src/tiled/editabletile.cpp, src/tiled/editabletile.h, src/tiled/editabletileset.cpp, src/tiled/editabletileset.h, src/tiled/scriptimage.cpp, src/tiled/scriptimage.h, src/tiled/scriptmanager.cpp, src/tiled/scriptmodule.h, src/tiled/tiled.pro, src/tiled/tiled.qbs
Now a script can create an image, either directly or by loading from a file or data or based on raw data. Then, the image can be passed to Tileset.loadFromImage or Tile.setImage.
Related to issue #2695
=> Scripting: Enabled creating images and using them

src/tiled/project.cpp
Extension path was getting saved under the `extensionsPath` key
but getting read from the `extensionsFolder` key.
Read the value back from the written `extensionsPath` key.
=> Fix loading extension path from project config

src/tiled/abstractobjecttool.cpp, src/tiled/abstractobjecttool.h, src/tiled/editpolygontool.cpp, src/tiled/objectselectiontool.cpp, src/tiled/preferences.h, src/tiled/preferencesdialog.cpp, src/tiled/preferencesdialog.ui
Previously when clicking objects it would always take the top-most object from any visible and unlocked layer.
This new option allows changing that such that when available, an object from one of the currently selected layers is preferred. It can also be set to only do this, when the highlighting of current layer option is enabled (the new default).
This would close #354.
=> Added option to change object selection behavior

src/plugins/python/find_python.pri
The default pkg-config module no longer contains -lpython3.8.
Reference: https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build
=> Fix Python plugin linking issue with Python 3.8

dist/win/installer.wxs, src/libtiled/maprenderer.cpp, src/plugins/gmx/gmxplugin.cpp, src/plugins/plugins.pro, src/plugins/plugins.qbs, src/plugins/yy/jsonwriter.cpp, src/plugins/yy/jsonwriter.h, src/plugins/yy/plugin.json, src/plugins/yy/yy.pro, src/plugins/yy/yy.qbs, src/plugins/yy/yy_global.h, src/plugins/yy/yyplugin.cpp, src/plugins/yy/yyplugin.h
Closes #1642
Quite a bit of work done, but some tasks remain and no testing was done at all yet.
=> Added export to GameMaker Studio 2

docs/reference/support-for-tmx-maps.rst
I am a developer on both pytiled-parser and Arcade Python libraries.
Both have just finished undergoing re-writes to only suppport the JSON file format as opposed to TMX, so clarifying that here. At time of writing Arcade does not yet have those changes in a release, but will be included in the next version, which I've made note of in the updated description.
=> Update pytiled-parser and arcade description in docs

docs/scripting-doc/index.d.ts
@MrMasterplan, I noticed there was a "TiledImage" class and namespace being defined, but actually Tiled registers this class as just `Image`:
```c++
globalObject.setProperty(QStringLiteral("Image"), mEngine->newQMetaObject<ScriptImage>());
```
It could be that "TiledImage" was chosen on purpose, so I've opened a PR for this. Do you see any issues with this change?
=> docs: Extended TypeScript API definitions

docs/scripting-doc/index.d.ts, docs/scripting-doc/package.json, docs/scripting-doc/tsconfig.json
Setting some compiler options disables loading the DOM definitions.
I found the solution here: https://stackoverflow.com/questions/52850309/how-to-disable-global-variable-from-lib-dom-d-ts
=> Tsconfig change allows Image to be used

src/tiled/clipboardmanager.cpp
Fix https://github.com/mapeditor/tiled/issues/2874
Stamp tool has code that handles staggered maps, however it doesn't trigger if the stamp and the map have mismatch in their stagger index. In the case of copying it was always initialized to the default values instead of the values of the map copied from.
In my opinion some refactoring should take place, like forcing these parameters to be in the constructor, to avoid this same issue in other places.
=> Fix copy tool failing on some staggered maps

src/libtiled/map.cpp, src/libtiled/map.h, src/libtiled/mapreader.cpp, src/libtiled/maprenderer.cpp, src/libtiled/varianttomapconverter.cpp, src/plugins/droidcraft/droidcraftplugin.cpp, src/plugins/flare/flareplugin.cpp, src/plugins/replicaisland/replicaislandplugin.cpp, src/plugins/tbin/tbinplugin.cpp, src/tiled/abstracttilefilltool.cpp, src/tiled/capturestamphelper.cpp, src/tiled/clipboardmanager.cpp, src/tiled/mapobjectitem.cpp, src/tiled/newmapdialog.cpp, src/tiled/stampbrush.cpp, src/tiled/templatesdock.cpp, src/tiled/tilecollisiondock.cpp, src/tiled/tilesetdock.cpp, src/tiled/tilestampmanager.cpp, tests/staggeredrenderer/test_staggeredrenderer.cpp
This way, it should be less error-prone to add new parameters, since they will be automatically included in copy constructor and in various other places where they are copied.
Related to issue #2874.
This refactor was rather more work than I had expected, due to the huge amount of places in the source code that are constructing a Map instance. It might be worth looking for ways to reduce that, but creating maps just kind of happens to be what Tiled does.
=> Refactor Map constructor

src/tiled/mapitem.cpp, src/tiled/mapscene.cpp, src/tiled/mapscene.h
Fixes #3124.
Before, parallax was causing group layers to be offset as well as non-group layers. Now, only non-group layers have the parallax offset, so that they can properly use their effective inherited parallax value.
Visually tested on the scene I included in the issue. Also, tested with a 2-layer inheritance: 0.8 * 0.5 * 0.5 = 0.2.
=> Fix inherited parallax values causing layers to display incorrectly

translations/tiled_ko.ts
I supplemented the existing translation file `tiled_ko.ts`.
Also, I maintained the unity with the existing translation as much as possible.
I checked the typos as much as possible.
I hope it helps you.
=> Update Translation Korean

src/tiled/changeselectedarea.h, src/tiled/document.cpp, src/tiled/document.h, src/tiled/undocommands.h
Changing the selected area is an undo command so that it can be undone, but since it does not actually modify the file it should not cause the file to get marked as modified.
Closes #3194
=> Ignore selection changes when marking a file as modified

src/tiled/mapscene.cpp, src/tiled/mapscene.h, src/tiled/tilecollisiondock.cpp, src/tiled/tilecollisiondock.h
Setting collision editor background color from tileset background color is working. However, when changing the tileset background color, the collision editor stays the same color until a new tile is opened.
Something I noticed is that when you change the tileset background, the tile that is open on the collision is unselected, and the collision editor stays open without a tile, which I'm thinking might be the reason the background is not updated.
Fixes #3070
=> [WIP] Set collision editor bg color to tileset bg color

docs/scripting-doc/index.d.ts, src/tiled/editablegrouplayer.cpp, src/tiled/editablegrouplayer.h, src/tiled/editablemap.cpp, src/tiled/editablemap.h
Iterating these arrays is more convenient than using the `layerCount` and `layerAt` functions.
=> Scripting: Added TileMap.layers and GroupLayer.layers

docs/manual/export-yy.rst, src/plugins/yy/yyplugin.cpp
Before assuming the name of an image file without its extension to be the name of the associated sprite, search the current and up to two parent directories for a *.yy meta file. If found, use its name without the file extension instead.
A custom "sprite" property may still override this feature and will also prevent file system crawling.
This enables a user to use the sprite image files directly from their game project for image layers without having to specify the custom "sprite" property or using a copy with a proper name, as GameMaker Studio2 uses some UUID naming scheme for asset files.
The search is extended to parent directories as sprites resources also may contain subdirectories for individual layers. By the same token, a user may store different versions of an asset in the same …
=> YY Plugin: Determine sprite names by looking for meta files

docs/reference/support-for-tmx-maps.rst
pytiled-parser and Arcade both previously only supported JSON maps, but have recently been updated to add support for TMX as well. This PR just removes the note of not having TMX support from them.
=> docs: Update pytiled-parser and Arcade description

src/tiled/adjusttileindexes.cpp, src/tiled/changetile.cpp, src/tiled/changetile.h
When a tileset image has changed size and existing tile IDs are auto-adjusted, also update tile types in addition to other metadata.
Fixes #3236
=> AdjustTileMetaData also updates tile types

docs/reference/support-for-tmx-maps.rst
python-tmx is no longer maintained, but the homepage links to
https://ulvl.github.io/ which has support for reading TMX.
pytmxloader appears to be the best/most up-to-date fork of
https://code.google.com/archive/p/pytmxloader/
Note that I have no idea how to "update" the i18n locales - it might be good to add a section to the docs about that, if needed.
=> docs: Update list of 3rd-party libraries

docs/reference/support-for-tmx-maps.rst
Just came across this, wasn't even looking for it.
=> docs: Add irrTiled to list of 3rd-party libraries

docs/reference/support-for-tmx-maps.rst
libGDX wiki URL on "Support for TMX maps" page on the docs is outdated. The new one is on [libGDX's official website](https://libgdx.com/wiki).
=> update libGDX wiki URL

docs/scripting-doc/index.d.ts
Hey. I was struggling to call `File.directoryEntries` in typescript due to `File` currently being an interface. Looks like this should be a namespace instead. I've tested the methods on this namespace version from typescript and all look fine.
=> docs: Changed File script API to a namespace so it can be accessed in TypeScript

NEWS.md, src/libtiled/maprenderer.cpp
Since the tinting is so expensive, we're now keeping up to 100 MB of tinted versions allocated.
=> Introduced caching of tinted pixmaps

src/libtiled/imagecache.cpp, src/libtiled/imagecache.h, src/libtiled/mapreader.cpp, src/libtiled/maptovariantconverter.cpp, src/libtiled/mapwriter.cpp, src/libtiled/tile.cpp, src/libtiled/tile.h, src/libtiled/tileset.cpp, src/libtiled/tileset.h, src/libtiled/varianttomapconverter.cpp, src/tiled/brokenlinks.cpp, src/tiled/changetile.cpp, src/tiled/changetile.h, src/tiled/changetileimagesource.cpp, src/tiled/changetileimagesource.h, src/tiled/editabletile.cpp, src/tiled/propertybrowser.cpp, src/tiled/tilesetdocument.cpp, src/tiled/tilesetdocument.h, src/tiled/undocommands.h
Now that we're storing a sub-rectangle for each tile, we can use it to avoid actually cutting out the tiles from the tileset image.
Changing of a tile's image rect now also has its own undo command, and the tile image rect property is visible also for tiles from tileset-image based tilesets, though not editable for now.
=> Use Tile::imageRect instead of cutting out tiles

NEWS.md, src/libtiled/layer.cpp, src/libtiled/layer.h, src/libtiled/objectgroup.cpp, src/libtiled/objectgroup.h, src/tiled/automapper.cpp, src/tiled/clipboardmanager.cpp, src/tiled/editablelayer.cpp, src/tiled/mapdocument.cpp, src/tiled/mapdocumentactionhandler.cpp, src/tiled/objectreferenceshelper.cpp, src/tiled/objectreferenceshelper.h, src/tiled/tiled.pro, src/tiled/tiled.qbs
Expands on f6bf60ff759a3c5a7ffd02cc1c0e02b7e97bf810. Now this behavior also applies to the following actions:
* Duplicate Layer
* Duplicate Objects
* Layer via Copy
* When the AutoMapper places objects
See issue #3361
=> Keep object connections when duplicating as well

src/libtiled/varianttomapconverter.cpp
I was able to reproduce the bug #3424 and made an attempt to fix the issue.
I added the necessary code to load the "repeatx" and the "repeaty" property of ImageLayer correctly from tmj/json.
=> Fixed "repeatx" and "repeaty" of ImageLayer for json

src/libtiled/maptovariantconverter.cpp
After the 1.8 compatibility mode was added in 1.9, `toVariant(Map)` was updated to use `FileFormat::versionString()`, but `toVariant(Tileset)` was not and was still always writing out "1.8".
=> MapToVariantConverter: Write out the correct version for Tilesets

docs/reference/support-for-tmx-maps.rst
1. `tiled` library for use with Dart programming language;
2. `flame_tiled` for incorporating Tiled maps into the Flame game engine.
=> Added mention of 2 tiled libraries

NEWS.md, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h
Fixes #3452 by attempting to use the default "{Type} Layer {Number}" name, incrementing {Number} if any collisions occur.
=> Smartly choose a new layer name to prevent duplicate names

NEWS.md, src/tiled/editabletile.cpp
- fixes #3495 by handling the case where a user calls `tile.objectGroup = null`, allowing the user to clear out assigned collision shape objects
=> Allow a tile's object group (collision objects) be cleared via script

src/tiled/objectselectionitem.cpp, src/tiled/objectselectionitem.h
- fixes #3400 which notes that the labels for points are attached to a world coordinate, rather than a screenspace coordinate
- the issue came about when points were changed from having a world-fixed size to now having a screen-fixed size, such that the annotation remains the same size when changing the zoom level of the map editor
- one minor issue with this fix is that the painterScale used seems to be one "frame" behind whenever we are re-rendering due to a zoom level change; this corrects itself on the next non-cached repaint (for example, by panning the map editor)
- I have a prototype of a different fix where this one-frame lag doesn't occur but a different issue occurs; the bounding box of the label does not match where it is actually rendered and thus Qt graphics does not allow it …
=> Fix point label placement to stick near the point object

src/tiled/layerdock.cpp, src/tiled/tilesetview.cpp
This PR fixes #3444 by adding a way to select all the tiles in the tileset view (useful for treating an entire tileset as a conglomerate stamp) and by adding the pre-existing "select all layers" action to the right-click context menu of the layers list.
=> Add more "select all" capabilities for the tileset view and layer view

CONTRIBUTING.md, docs/manual/automapping.rst, docs/manual/export-yy.rst, docs/manual/projects.rst, docs/manual/worlds.rst
1. Adds trailing punctuation to a few lines that were missing it.
2. Fixes a few misspelled words.
3. Changes a few word choices to match the text used elsewhere in the manual (example: `non-walkable` to `unwalkable`).
4. Adds, removes, or changes some punctuation within sentences (often a comma into a semi-colon) or between words (example: `rightclicking` to `right-clicking`).
I noticed that lines were typically wrapped around the 72-ish column in several files, so tried to maintain that style in the changed lines.
=> Fix minor grammar and spelling errors in docs

docs/scripting-doc/index.d.ts, src/tiled/editablemap.cpp, src/tiled/editablemap.h
This new property has type `region` instead of `SelectedArea`, with the goal of unifying region values in the JS API.
Remaining issues with this change:
* It is not possible to assign a rectangle, for example created by `Qt.rect` to `selectedRegion`. I'm not sure if this can be fixed by adding overloads for the setter.
* It is not possible to create a new region value from script. Probably requires adding something like `tiled.region(...)` that can create either a empty or rectangular region.
=> Scripting: Replaced TileMap.selectedArea with TileMap.selectedRegion

qbs/imports/TiledPlugin.qbs, qbs/imports/TiledQtGuiApplication.qbs, src/libtiled/libtiled.qbs, src/libtiled/pluginmanager.cpp, src/libtiledquick/libtiledquick.qbs, src/tiled/languagemanager.cpp, src/tiled/libtilededitor.qbs, src/tiledquick/tiledquick.qbs, tiled.qbs, translations/translations.qbs
The new `windowsLayout` project option is enabled by default on Windows.
If this opotion is disabled manually, installed files will follow the Unix-like FHS (Filesystem Hierarchy Standard).
*UPDATE*: I am using these changes as a patch to [add](https://github.com/msys2/MINGW-packages/pull/15464) the `tiled` package in the [MSYS2](https://www.msys2.org/) distribution.
It will be great if similar changes are accepted into the code base of the original project.
=> Added Windows layout management option

NEWS.md, src/tiled/imagecolorpickerwidget.cpp, src/tiled/propertytypeseditor.cpp, src/tiled/propertytypeseditor.h, src/tiled/utils.cpp, src/tiled/utils.h
The hack that was used to keep the `QMenu` visible with Qt 5 no longer worked, since it seems Qt 6 calls `destroy()` instead of `hide()` on the menu.
The `QMenu` is now replaced by a popup with checkboxes.
=> Qt 6: Fixed behavior of "Class of" selection popup

NEWS.md, docs/reference/json-map-format.rst, docs/reference/tmx-changelog.rst, docs/reference/tmx-map-format.rst, src/libtiled/fileformat.cpp, src/libtiled/fileformat.h, src/libtiled/maptovariantconverter.cpp, src/libtiled/mapwriter.cpp, src/libtiled/tiled.cpp, src/libtiled/tiled.h, src/plugins/lua/luaplugin.cpp, src/tiled/project.h, src/tiled/projectpropertiesdialog.cpp
Since Tiled 1.9, the "type" attribute was written out as "class", for consistency with the new "class" attribute added to other elements. This change affected the TMX, JSON and Lua formats. For compatibility, a "Compatibility Version" option was introduced for projects, which could be used to restore compatibility with Tiled 1.8.
This change has unfortunately caused considerable confusion, and many existing libraries and frameworks supporting Tiled files still do not support "class" even half a year after this change. Renaming this attribute just for consistency was clearly a mistake.
This change restores the compatibility with Tiled 1.8 by default, using "class" only in new places but reverting back to the older "type" attribute for map objects and tiles. This is not consistent, but …
=> Restored Tiled 1.8 file format compatibility by default

.github/workflows/packages.yml, NEWS.md
* https://github.com/getsentry/sentry-native/releases/tag/0.5.3
* https://github.com/getsentry/sentry-native/releases/tag/0.5.4
=> AppImage: Updated to Sentry 0.5.4

src/tiled/propertytypeseditor.cpp
It used to be rendered because a menu was attached. Now that there is no menu attached, we need to override some things to fake it.
=> Bring back the arrow down on the "Class of" button

src/tiled/mainwindow.cpp, src/tiled/mainwindow.h
Unfortunately, a regression in Qt 6.3 is causing the hiding of status bar widgets when switching editors to hide the news button.
Fix proposed in https://codereview.qt-project.org/c/qt/qtbase/+/460302
=> Qt 6: Fixed visibility of status bar News button

.github/workflows/packages.yml, appveyor.yml, dist/distribute.qbs, dist/win/installer.wxs, src/tiled/newsbutton.h, src/tiled/tiledapplication.cpp, src/tiled/tiledapplication.h
Builds against Qt 5.15.2 will remain available for now for older systems.
=> Updated release builds to Qt 6.4.2

NEWS.md, src/libtiled/isometricrenderer.cpp, src/libtiled/isometricrenderer.h, src/libtiled/mapobject.cpp, src/libtiled/mapobject.h, src/libtiled/maprenderer.h, src/libtiled/minimaprenderer.cpp, src/libtiled/orthogonalrenderer.cpp, src/libtiled/orthogonalrenderer.h, src/libtiled/propertytype.cpp, src/libtiled/propertytype.h, src/tiled/mapobjectitem.cpp, src/tiled/mapobjectitem.h, src/tiled/propertytypeseditor.cpp, src/tiled/propertytypeseditor.h, src/tmxrasterizer/tmxrasterizer.cpp, src/tmxviewer/tmxviewer.cpp
~Respect this setting for Point objects as well?~
Fix #3312
Feel free to squash if merged
=> Add drawFill property to custom types to allow disabling the color fill

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/regionvaluetype.cpp, src/tiled/regionvaluetype.h, src/tiled/scriptmanager.cpp
Returns this region as an array of contiguous regions, based on 8-way connectivity (regions touching each other diagonally are considered contiguous).
This was an easy to provide convenience function since the functionality already existed for AutoMapping to find the rules in a rule map.
=> Scripting: Added region.contiguousRegions()

docs/scripting-doc/index.d.ts
While working on an extension, I noticed the `tickInterval` property was not working as expected on a QDoubleSpinBox.  I checked the docs and the name is currently `singleStep`.
See https://doc.qt.io/qt-5/qdoublespinbox.html#singleStep-prop
=> docs: Fix QDoubleSpinBox step value property name

NEWS.md, src/libtiled/isometricrenderer.cpp, src/libtiled/maprenderer.cpp, src/libtiled/orthogonalrenderer.cpp, src/libtiledquick/tilelayeritem.cpp
Work around an issue introduced in Qt 6.4.1 ([QTBUG-111416](https://bugreports.qt.io/browse/QTBUG-111416)) by not using `QPainter::drawPixmapFragments` in OpenGL mode. This makes rendering tiles a bit less efficient, but at least it works.
Closes #3578
=> Qt 6: Fixed tile rendering when OpenGL is enabled

NEWS.md, docs/manual/preferences.rst, src/tiled/issuescounter.cpp, src/tiled/mainwindow.cpp, src/tiled/preferences.cpp, src/tiled/preferences.h, src/tiled/preferencesdialog.cpp, src/tiled/preferencesdialog.ui, src/tiled/shortcutsettingspage.cpp, src/tiled/stylehelper.cpp, src/tiled/stylehelper.h, src/tiled/tiledproxystyle.cpp, src/tiled/wangsetmodel.cpp, src/tiledapp/main.cpp
=> Added option to choose a custom interface font

NEWS.md, src/tiled/mapeditor.cpp, src/tiled/mapeditor.h, src/tiled/mapview.cpp, src/tiled/mapview.h
The `QOpenGLWidget` causes the surface type for the window to switch to `OpenGLSurface`, but it doesn't automatically switch back to `RasterSurface` when the last `QOpenGLWidget` is deleted again.
Closes #3584
=> Fixed remaining lag after switching off hardware acceleration

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/abstractobjecttool.cpp, src/tiled/abstractobjecttool.h, src/tiled/abstracttiletool.cpp, src/tiled/abstracttool.cpp, src/tiled/abstracttool.h, src/tiled/editablelayer.h, src/tiled/layeroffsettool.cpp, src/tiled/layeroffsettool.h, src/tiled/scriptedtool.cpp
This new property specifies the target layer type for which this tool should be enabled, providing a convenient alternative to implementing `Tool.updateEnabledState`.
Closes #3248
=> Scripting: Added Tool.targetLayerType

src/tiled/mainwindow.ui
=> Fix mistake in Search Actions where the shortcut Ctrl+Shift+P was marked as translatable 

docs/scripting-doc/index.d.ts
I realized this was missing today despite being linked to elsewhere in the scripting doc.
=> Add missing doc for html property on QTextEdit and fix missing parameter in Dialog.addImage

NEWS.md, src/tiled/automapper.cpp
It was checking overlap per output layer defined in the rule map, rather than overlap per target layer, as would be expected.
Closes #3551
=> AutoMapping: Fixed NoOverlappingOutput in case of multiple output indices

NEWS.md, src/tiled/automapper.cpp, src/tiled/automapper.h, src/tiled/automappingutils.cpp, src/tiled/automappingutils.h, tests/automapping/test_automapping.cpp
With this change, output object layers are taken into account when determining the rule output regions.
The support for outputting objects by AutoMapping is still lacking support for many cases, like polygon/polyline objects or the object alignment setting, but it is at least meant to work for basic rectangle or tile objects.
This change also adjusts tileRegionOfObjectGroup to the change that made object position and size be stored in pixels rather than tiles (55e77677523ba93f797f6723fb22a86a28d38932), as was already done for objectsToErase before (521a40a5dac6552c943f8639f761a8b1e7535b82).
Closes #3473
=> AutoMapping: Fixed automatic output regions for object output

NEWS.md, docs/manual/automapping.rst, src/tiled/automapper.cpp, src/tiled/automapper.h, src/tiled/automapperwrapper.cpp, src/tiled/propertybrowser.cpp
Rather than each output set always having equal probability, it is now possible to specify a probability for each output set, using a custom "Probability" property on any of its layers (when multiple layers in an output set have a "Probability" property, the last / top-most one wins).
The probability between output sets is relative and defaults to 1.0. So for example, when setting it to 2.0 for some output set, it will be twice as likely to be picked as any other output set.
Closes #3179
=> AutoMapping: Added support for output set probability

docs/manual/automapping.md
Changed property names to **bold** from `code`, so that it's clearer what's a value or text you type and what's a property.
=> Automapping docs: Improve styling, minor wording fix

NEWS.md, src/tiled/editablemap.cpp, src/tiled/mapscene.cpp, src/tiled/mapscene.h, src/tiled/objectreferenceitem.h, src/tiled/objectselectionitem.cpp, src/tiled/objectselectionitem.h
When changing the custom application font, the object labels were not immediately updating their size.
=> Fixed object labels to adjust to application font changes

NEWS.md, src/tiled/bucketfilltool.cpp, src/tiled/stampbrush.cpp, src/tiled/wangbrush.cpp, src/tiled/wangfiller.cpp, src/tiled/wangfiller.h
Now Hexagonal (Staggered) maps are treated the same way as Isometric (Staggered) maps, which might be better than treating them as orthogonal maps. It at least fixes the behavior when "hex side length" is 0, but it does not mean hexagonal maps are actually supported by the Terrain Brush.
Closes #3617
=> Tweaked handling of Hexagonal (Staggered) maps by Terrain Brush

NEWS.md, src/libtiled/map.cpp, src/tiled/capturestamphelper.cpp, src/tiled/stampbrush.cpp
While shifting rows or columns, the layer positions were not being taken into account.
Closes #3431
=> Fixed tile stamp getting messed up on staggered maps in some cases

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/editableproject.cpp, src/tiled/editableproject.h, src/tiled/libtilededitor.qbs, src/tiled/scriptmodule.cpp, src/tiled/scriptmodule.h
=> Expose basic properties of Tiled projects to scripting

NEWS.md, src/tiled/utils.cpp, src/tiled/utils.h
Qt 6 no longer caches theme icons when they could not be found, resulting in many expensive icon searches each time the icon is requested again.
Introduced another icon cache to resolve this problem.
=> Qt 6 / Linux: Improved startup time for some icon themes

.github/workflows/packages.yml
Debug information was getting installed after using the convenience install properties in 46c447422209929b14e6622dec51942d5bbe09b1. However, we do not want to include these files in the AppImage since they make it very big.
=> GitHub Actions: Avoid shipping debug information in AppImage

NEWS.md, src/tiled/scriptdialog.cpp, src/tiled/scriptdialog.h
When a new row was created automatically when adding a widget, it was failing to remember the type of that widget, since `addNewRow` was called after setting `m_lastWidgetTypeName`.
Now the last widget type is set in addDialogWidget instead. Also, we no longer compare the type names but just compare the `QMetaObject` pointers directly.
Also fixed a problem in `ScriptDialog::deleteAllDialogs`, which iterated the `sDialogInstances` container while it was also getting modified as each dialog was deleted.
Closes #3607
=> Scripting: Fixed behavior of Dialog.SameWidgetRows

docs/scripting-doc/CHANGELOG.md, docs/scripting-doc/index.d.ts, docs/scripting-doc/package-lock.json, docs/scripting-doc/package.json
The constructor overload taking a shape was missing. It appears to have been available since Tiled 1.3, when the scripting API was added.
=> docs: Added missing MapObject constructor

NEWS.md, src/tiled/layerdock.cpp
This reverts commit 0de0f20e304bbed4d8c52e4cc09586bb12d34c5a.
This shortcut was only provided for backwards compatibility, but it often conflicts with using Space for panning the map view and since 359dcb93f3a4248e0380f9965ab9dd6b44308eb9 there are global shortcuts available for toggling layer visility and locked status, making this shortcut no longer necessary.
See issue #3672.
=> Revert "Re-enabled Space for toggling layer visibility"

NEWS.md, src/libtiled/mapobject.cpp, src/libtiled/objectgroup.cpp, src/libtiled/objectgroup.h, src/tiled/mainwindow.cpp, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h, src/tiled/offsetlayer.cpp, src/tiled/offsetlayer.h, src/tiled/offsetmapdialog.cpp, src/tiled/offsetmapdialog.h
* Make sure all objects are offset when choosing "Whole Map" as bounds.
* Take into account tile object size and alignment when determining whether an object is within the area to offset.
* <s>Support wrapping for infinite maps, where it will wrap based roughly on tile layer contents (chunk-based).</s>
=> Fixed some issues with the Offset Map action related to objects

NEWS.md, docs/manual/export-tscn.rst, src/plugins/tscn/tscnplugin.cpp
This is my attempt at adding feature #3652.
Tile properties are exported as custom property layer 0, named "Properties".
Allows code like: `get_custom_data("Properties").get(<Property>)`
Feedback welcome.
=> Add custom tile properties to Godot .tscn export format

docs/reference/support-for-tmx-maps.rst
This PR updates the mention of [Castle Game Engine](https://castle-engine.io/) in Tiled to link to our most recommended page to read about how to use CGE + Tiled: https://castle-engine.io/tiled_maps 
Lately we've done a lot of enhancements and optimizations for Tiled handling recently, see news:
- https://castle-engine.io/wp/2023/05/21/tiled-maps-examples-updated-see-the-new-strategy-game-demo-api-and-docs-improvements-how-to-determine-tile-picked-by-mouse-and-more/
- https://castle-engine.io/wp/2023/03/25/new-component-to-place-tiled-map-in-a-viewport/
- https://castle-engine.io/wp/2023/01/22/big-improvements-and-optimizations-for-tiled-maps-handling-in-tcastlescene/
Thank you for making Tiled -- we're happy to recommend this to CGE users as the best way to design 2D maps!
=> Update Castle Game Engine to link to manual

.github/workflows/packages.yml, NEWS.md
=> macOS: Try creating an x64_64 + arm64 fat binary

NEWS.md, docs/scripting-doc/index.d.ts, src/libtiled/wangset.cpp, src/libtiled/wangset.h, src/tiled/editablewangset.h, src/tiled/wangbrush.cpp
Moved implementation in `WangBrush` to `WangSet`, so that it can be reused by the script API.
=> Scripting: Added WangSet.effectiveTypeForColor

NEWS.md, docs/manual/editing-tile-layers.rst, src/tiled/geometry.cpp, src/tiled/geometry.h, src/tiled/shapefilltool.cpp, src/tiled/stampbrush.cpp
I've replaced the ellipse drawing algorithms with implementations by Zingl Alois, originally written in 2012 and published under MIT license.
This addresses several issues with the previously used implementations of pointsOnEllipse and ellipseRegion:
* Ellipses no longer degrade when very large (near 2000 tiles in size).
* No more gaps in the ellipse for some sizes.
* Shape Fill tool can now actually draw circles of equal width and height and can draw both even and odd sized ellipses.
The Shape Fill tool was adjusted such that drawing ellipses work in bounding-box mode by default. The Alt modifier now toggles to center + radius mode, which also applies when drawing rectangles.
Closes #3775
=> Fixed several issues with drawing ellipses

NEWS.md, docs/manual/terrain.rst, docs/reference/tmx-map-format.rst, docs/scripting-doc/index.d.ts, src/libtiled/grid.h, src/libtiled/wangset.cpp, src/libtiled/wangset.h, src/tiled/abstracttilefilltool.cpp, src/tiled/randompicker.h, src/tiled/stampbrush.cpp, src/tiled/tilelayerwangedit.cpp, src/tiled/tilelayerwangedit.h, src/tiled/wangbrush.cpp, src/tiled/wangfiller.cpp, src/tiled/wangfiller.h
Mostly removing the special handling for erasing and changing the way filling is implemented. Should also improve the new TileLayerWangEdit behavior when erasing.
=> Improve WangBrush and TileLayerWangEdit behavior with empty color

.github/workflows/packages.yml, appveyor.yml, dist/win/installer.qbs, src/plugins/python/python.qbs
This should fix the macOS builds, which were using Qbs from Qt Creator versions 5.0.3 and 7.0.2, which are no longer available to download.
Using Qt Creator 5.0.3 was necessary on old versions of macOS since it was the last release using Qt 5. We should be able to use a newer version even when building for macOS 10.12-10.13.
=> CI: Updated to Qbs 2.0.2

NEWS.md, src/tiled/mapobjectmodel.cpp
When an unnamed tile object refers to single images (from an image collection tileset), the image base name will now be displayed in the Objects view.
This can help identify objects and also allows the filter to work with the image names for these objects:
=> Display the image base name for unnamed tile objects

NEWS.md, src/libtiled/properties.h, src/tiled/propertytypeseditor.cpp
This crash was caused by an infinite recursion happening when changing top-level FilePath values. It only affected Qt 6 builds, because two QVariant values that both hold a FilePath value always compared as unequal due to FilePath not defining a comparision operator.
In addition to adding the comparison operator, I've also added a condition to the updating of the property value. It should only be necessary to update the top-level value when a nested value was changed. Further more, it now sets mUpdatingDetails as another protection against recursive calls.
For completeness I've also added the comparision operator to PropertyValue and ObjectRef, though they would not have caused problems in this context since they're not used as property display values.
Closes #3783
=> Fixed crash when changing file member of custom class

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/scriptdialog.cpp, src/tiled/scriptdialog.h, src/tiled/scriptmodule.cpp, src/tiled/scriptmodule.h
Fix #3537 
I didn't write the scripting doc yet but I figured I could put up the C++ code for people to try & for review before I do that.
=> Add file open / save prompts in scripting API

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/editablemapobject.cpp, src/tiled/editablemapobject.h, src/tiled/geometry.cpp, src/tiled/geometry.h, src/tiled/libtilededitor.qbs, src/tiled/scriptgeometry.cpp, src/tiled/scriptgeometry.h, src/tiled/scriptmanager.cpp
Providing access from scripts to the existing line and ellipse rendering functions.
=> Scripting: Added Geometry interface with line and ellipse helpers

docs/scripting-doc/index.d.ts, src/tiled/abstractworldtool.cpp, src/tiled/mapscene.cpp, src/tiled/scriptedtool.cpp
=> Fixed Tool.updateEnabledState behavior and related changes

NEWS.md, src/tiled/abstracttilefilltool.cpp, src/tiled/abstracttilefilltool.h, src/tiled/bucketfilltool.cpp, src/tiled/shapefilltool.cpp, src/tiled/wangbrush.cpp, src/tiled/wangbrush.h, src/tiled/wangfiller.cpp, src/tiled/wangfiller.h
* These locations are now marked in red
* The text "Missing terrain transition" appears on the status bar
=> Provide feedback when the Terrain Brush can't find some tiles

NEWS.md, docs/manual/custom-properties.rst, src/qtpropertybrowser/src/qtpropertymanager.cpp, src/tiled/propertytypeseditor.cpp, tests/properties/test_properties.cpp, translations/tiled_ar_DZ.ts, translations/tiled_bg.ts, translations/tiled_cs.ts, translations/tiled_de.ts, translations/tiled_en.ts, translations/tiled_es.ts, translations/tiled_fi.ts, translations/tiled_fr.ts, translations/tiled_he.ts, translations/tiled_hu.ts, translations/tiled_it.ts, translations/tiled_ja.ts, translations/tiled_ko.ts, translations/tiled_nb.ts, translations/tiled_nl.ts, translations/tiled_pl.ts, translations/tiled_pt.ts, translations/tiled_pt_PT.ts, translations/tiled_ru.ts, translations/tiled_sv.ts, translations/tiled_th.ts, translations/tiled_tr.ts, translations/tiled_uk.ts, translations/tiled_zh_CN.ts, translations/tiled_zh_TW.ts
Due to the use of a 32-bit int to store the flags, the maximum number of flags is actually 30 rather than 32. When more entries are added, the editing of enum values breaks entirely.
The translations have been updated to use a parameter for the maximum number of flags in an enum, to make it easier to adjust this value when it might be increased in the future.
Closes #3658
=> Fixed the entry limit for enums used as flags to be 31

NEWS.md, src/libtiled/tileset.cpp, src/libtiled/tileset.h, src/libtiled/varianttomapconverter.cpp
Since Tiled 1.7, the order of tiles in the tileset file determines the display order. But this should not be the case for tilesets stored in the old JSON format (which was replaced in Tiled 1.2), since it used an object with the tile IDs as string keys for storing tile meta-data and these keys get sorted alphabetically. This was resulting in tiles with associated data getting displayed in an order like "1, 10, 11, 12, 13, ..., 2, 21, ...".
=> JSON format: Fixed tile order when loading a tileset using the old format

docs/scripting-doc/index.d.ts
I added doc for this in a past PR, but it wasn't showing on the site: 
https://www.mapeditor.org/docs/scripting/classes/Dialog.html#exec
=> fix typo in scripting doc for Dialog.exec()

docs/scripting-doc/index.d.ts
Fix docs from https://github.com/mapeditor/tiled/pull/3782 and https://github.com/mapeditor/tiled/pull/3384
=> add @since tags to promptOpen*/promptSave* scripting methods, add link to FileFilter from FileEdit.filter

NEWS.md, src/tmxviewer/main.cpp, src/tmxviewer/tmxviewer.cpp
The viewer can now read any default-enabled map format, which currently only covers the JSON map format in addition to TMX.
Closes #3866
=> tmxviewer: Added support for viewing JSON maps

NEWS.md, src/tmxrasterizer/main.cpp, src/tmxrasterizer/tmxrasterizer.cpp, src/tmxrasterizer/tmxrasterizer.h
These allow exporting animated maps as multiple numbered images, which can be combined into a GIF or other format using another tool.
The `--advance-animations` parameter stays for compatibility, and determines the time of the first exported frame, whereas `--frame-duration` determines the time between each frame.
Example usage:
```
tmxrasterizer desert.tmx desert.png --frames 5
```
The above will create the following list of images:
```
desert0.png
desert1.png
desert2.png
desert3.png
desert4.png
```
And each rendered frame will have advanced by another 100ms from the previous one (the default frame duration).
This is related to #1433, though it does not actually create a GIF (but other animation formats may be preferred anyway).
=> tmxrasterizer: Added --frames and --frame-duration arguments

NEWS.md, src/tiled/project.h, src/tiled/projectmanager.h, src/tiledapp/main.cpp
This allows the `--export-map` and `--export-tileset` parameters to use file formats defined by extensions in the project, and also enables handling of custom types.
Closes #3797
=> Added `--project` command-line parameter for use when exporting

.github/workflows/packages.yml, NEWS.md
Not updating to Sentry 0.7 for now because it changes the default backend to `crashpad`. Tiled should probably use that as well, but for that we need to figure out how to ship its crash handler.
=> AppImage: Updated to Sentry 0.6.7

docs/scripting-doc/index.d.ts, src/tiled/editableworld.cpp, src/tiled/editableworld.h
In the newly added world scripting feature #3859 , there's a chance that users could  call `containsMap()` with a TileMap and receive a false negative response, as it seems like the TileMap will be coerced to a string.  To avoid this, introduce `containsMap(map:TileMap)` which will take the file name of the given tilemap.
=> add containsMap(map:TileMap) scripting method

NEWS.md, src/plugins/tscn/tscnplugin.cpp
The exporter was incorrectly using the collision object's X and Y position as a part of the tile's center. Fixed the calculation for both rectangles and polygons. Tested on a local Windows build.
=> Godot exporter collision fix

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/editableimagelayer.cpp, src/tiled/editableimagelayer.h, src/tiled/editabletile.cpp, src/tiled/editabletile.h, src/tiled/editabletileset.cpp, src/tiled/editabletileset.h
Usually one could load the image based on `Tile.imageFileName`, but when a tile's image has been set directly using `Tile.setImage`, this is not possible. This can happen for example when an importer has used this function since there was no external image file to refer to, or it used an unsupported image format.
`Tile.image` now provides convenient access to the tile's image, falling back to the tileset's image when the tile has no individual image.
As such, this function also provides access to the tileset's image, which would ideally be available through `Tileset.image`, but this property was already taken and used for the image file name. To free up this property in the future it is now deprecated. Extensions should switch to the new `Tileset.imageFileName` property.
Part of issue …
=> Scripting: Added Tile.image for accessing a tile's image data

src/libtiled/filesystemwatcher.cpp, src/libtiled/filesystemwatcher.h, src/libtiled/tilesetmanager.cpp, src/libtiled/tilesetmanager.h
The TilesetManager no longer watches by default, it now relies on the Tiled Preferences to enable this. This makes sure, that other tools, like the tmxrasterizer, for which it makes no sense to watch the file, will not watch the files (and won't trigger SELinux pop-ups on Fedora...).
=> tmxrasterizer: Don't watch tileset images for changes

.github/workflows/docs.yml, .github/workflows/macos-latest.yml, .github/workflows/packages.yml, .github/workflows/upload-to-itch.yml
Avoids warnings and should be significantly faster.
=> GitHub Actions: Updated upload/download-artifact versions

NEWS.md, docs/manual/custom-properties.rst, docs/manual/export-tscn.rst, src/plugins/tscn/tscnplugin.cpp
Now supporting objects in the Godot 4 exporter initially added in pull #3550.
Video showing it off here: https://www.youtube.com/watch?v=3UfOOdepDDw
=> Added object support to Godot exporter

src/libtiled/tilelayer.h, src/tiled/automapper.cpp, src/tiled/automapper.h, src/tiled/automappingutils.cpp, src/tiled/automappingutils.h
This change introduces a "compileOutputSet" step which is executed as part of collecting the rules. In this step, each rule only receives as possible outputs the output indexes that are non-empty for the region of that rule.
This makes it much easier to add output variation to only some of the rules. Previously, due to the possibility of empty outputs being chosen, having rules with various amounts of variation required setting up separate rule maps.
Closes #3523
=> Automapping: Ignore empty outputs per-rule

NEWS.md, docs/manual/automapping.md, src/libtiled/tilelayer.h, src/tiled/automapper.cpp, src/tiled/automapper.h, src/tiled/automappingutils.cpp, src/tiled/automappingutils.h, tests/automapping/option-ignore-lock/map-result.tmx, tests/automapping/option-ignore-lock/map.tmx, tests/automapping/option-ignore-lock/rules.tmx, tests/automapping/test_automapping.cpp
This change introduces a "compileOutputSet" step which is executed as part of collecting the rules. In this step, each rule only receives as possible outputs the output indexes that are non-empty for the region of that rule.
This makes it much easier to add output variation to only some of the rules. Previously, due to the possibility of empty outputs being chosen, having rules with various amounts of variation required setting up separate rule maps.
Closes #3523
This PR supercedes #3894, which was merged accidentally.
=> Automapping ignore empty outputs

NEWS.md, src/libtiled/wangset.cpp, src/libtiled/wangset.h, src/tiled/changetilewangid.cpp, src/tiled/tilesetview.cpp, src/tiled/wangdock.cpp, src/tiled/wangfiller.cpp
Changing the type of a Terrain Set does not clear no longer relevant bits from each tile, in order to allow changing the type back and forth without destroying this information.
However, this caused the terrain overlays to be confusing and terrain tools to behave erratically. Now, the irrelevant bits of each tile's terrain info is masked out where appropriate.
Closes #3204
Closes #3260
=> Terrain tools now ignore irrelevant labels

src/tiled/tileseteditor.cpp
On startup there is no tileset open, so these actions should be disabled. Normally they would not be visible anyway, but they appear in the "Action Search" popup when enabled.
=> Disable the add/remove tile actions on startup

NEWS.md, src/tiled/exporthelper.cpp
=> Resolve class members when exporting and the relevant option is enabled

NEWS.md, src/tiled/actionsearch.cpp
Issue introduced in fb2390aeb01eb183da8a5adc1970cbef1c1043f9.
We do need to call `QStaticText::prepare` in this case, because we need to know its width in the small font, before painting the text.
=> Fixed alignment of shortcuts in action search

NEWS.md, src/tiled/changemapobject.cpp, src/tiled/editableasset.cpp, src/tiled/editableasset.h, src/tiled/editablemap.cpp, src/tiled/editablemap.h, src/tiled/editableproject.cpp, src/tiled/editabletileset.cpp, src/tiled/editabletileset.h, src/tiled/editableworld.cpp
When assigning a new map or tileset created from a script to `tiled.activeAsset`, the necessary signals were not connected. This broke the signals from `EditableMap` and it also caused certain ownership transfers from JS to C++ to never take place. The latter could in turn lead to dangling pointers to objects after they were deleted by the garbage collector.
Thanks to @eishiya for discovering this issue!
=> Fixed possible crash after assigning to tiled.activeAsset

NEWS.md, dist/linux/AppRun
The check whether the file existed was missing quotes.
Closes #3914
=> AppImage: Fixed ability to open paths with spaces from the CLI

NEWS.md, src/tiled/editor.cpp, src/tiled/editor.h, src/tiled/layermodel.cpp, src/tiled/mapdocument.cpp, src/tiled/mapobjectmodel.cpp, src/tiled/preferencesdialog.cpp, src/tiled/preferencesdialog.ui, src/tiled/tileseteditor.cpp
The option is disabled by default. When enabled, the behavior is a little bit nicer when creating many duplicates, since they now get numbered rather than adding "Copy Copy Copy..."
=> Made adding "Copy" when duplicating optional

.github/workflows/packages.yml, appveyor.yml
There is no longer a `master` branch.
=> CI: Use zstd release branch

docs/scripting-doc/index.d.ts
On Windows we need to remove three slashes.
=> docs: Small fix to snippet converting from Qt.Url to string

.github/workflows/packages.yml, snap/snapcraft.yaml
When using the 'version: git' approach, only the final snap knows the version, but it isn't known yet at compile time so Tiled always shows its version as "git".
=> snap: Fixed determining of the version

dist/linux/AppRun
After fixing the "is string non-empty" check in de5373af22885e2e75692c0, the script no longer did anything when no parameter was given...
As far as I could see, this check should just be removed.
See #3914
=> AppImage: Fixed ability to launch without parameters

src/tiled/tiledproxystyle.cpp
93f6fef14052e6797440e3f4c4a093f7507 had left it a little uncomfortable.
=> Tweaked margin between group box header and contents

src/tiled/projectdocument.cpp, src/tiled/projectdocument.h
Crash caused by a double-deletion of the `EditableProject`, since both the `Project` as well as the `ProjectDocument` classes were deleting it from their destructors (in the `Object` and `Document` superclasses, respectively).
This issue was introduced in 4244060c3fcb29ed514de5f419eb165a6cdbfb4f.
=> Scripting: Fixed crash after using tiled.project

NEWS.md, src/tiled/mapeditor.cpp, src/tiled/tilecollisiondock.cpp
Unless I'm missing something, this was only due to the missing ObjectReferenceTool instance in the tile collision editor.
Closes #3399
=> Fixed object assignment buttons in tile collision editor

NEWS.md, src/tiled/document.cpp, src/tiled/document.h, src/tiled/documentmanager.cpp, src/tiled/documentmanager.h
This should be mostly helpful for people using a VCS like Perforce or Subversion, which may require a file to be checked out or locked before it can be edited.
For now the read-only icon is a lock, which is common, but it may be confusing for Subversion users since they actually need to lock the file to make it writable.
=> Display read-only state of open files using a lock icon

src/tiled/document.cpp, src/tiled/documentmanager.cpp
Also fixed that when saving a file with a different name, the read-only flag was not refreshed.
Fix for c82539e331d7a90a3202e9f9b40f0486de84fdbd (see #3924).
=> Don't display non-existing files as read-only

src/tiled/abstractworldtool.cpp
The check on whether we could open the file wasn't checking what kind of file was getting loaded, which could lead to trying to add non-map files to a world.
=> Refuse to add files to a world that don't load as maps

NEWS.md, src/tiled/abstracttilefilltool.cpp, src/tiled/capturestamphelper.cpp, src/tiled/capturestamphelper.h, src/tiled/eraser.cpp, src/tiled/mapdocument.cpp, src/tiled/mapdocument.h, src/tiled/mapdocumentactionhandler.cpp, src/tiled/stampbrush.cpp, src/tiled/stampbrush.h
Implements #3961
Implementing this required a refactor of the state system in StampBrush.  Behavior and State were previously handled in the same property, which resulted both in wrong behavior when using capture and pressing the behavior keys (replicate by holding right click, start holding shift, release right click, the behavior wasn't set to line as it should have). This commit refactors this system by splitting State and Behavior in two enums and two properties, resulting in making the implemented feature possible, fixing behavior bugs, and future-proofing this system for expansion.
=> Stamp Brush right-click cut when Shift is held

src/tiled/aboutdialog.cpp, translations/tiled_ar_DZ.ts, translations/tiled_bg.ts, translations/tiled_cs.ts, translations/tiled_de.ts, translations/tiled_en.ts, translations/tiled_es.ts, translations/tiled_fi.ts, translations/tiled_fr.ts, translations/tiled_he.ts, translations/tiled_hi.ts, translations/tiled_hu.ts, translations/tiled_it.ts, translations/tiled_ja.ts, translations/tiled_ko.ts, translations/tiled_lv.ts, translations/tiled_mr.ts, translations/tiled_nb.ts, translations/tiled_nl.ts, translations/tiled_pl.ts, translations/tiled_pt.ts, translations/tiled_pt_PT.ts, translations/tiled_ru.ts, translations/tiled_sv.ts, translations/tiled_th.ts, translations/tiled_tr.ts, translations/tiled_uk.ts, translations/tiled_zh_CN.ts, translations/tiled_zh_TW.ts
This marks the string freeze for Tiled 1.11. For up-to-date translations, the summary is as follows:
Found 1450 source text(s) (44 new and 1406 already existing)
Removed 19 obsolete entries
Same-text heuristic provided 6 translation(s)
=> Update translation files

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/scriptimage.cpp, src/tiled/scriptimage.h
Since `Tile.image` can refer to a larger image, to get only the part representing the tile one needs to make a copy.
See #3960
=> docs: Provide snippet to get a tile's image

NEWS.md, docs/manual/keyboard-shortcuts.rst, src/tiled/mainwindow.ui
Leaving "Save All" with no default shortcut.
Closes #3933
=> Switch keyboard shortcut for "Save All" to "Save As"

.github/workflows/packages.yml
The `macos-11` image is now deprecated and doing blackouts.
Switched both to 'latest' to avoid them going stale again in the future.
AppImage remains on `ubuntu-20.04`, since it should generally be built on the oldest still supported version.
=> GitHub Actions: Updated macOS and Windows images

.github/workflows/packages.yml, NEWS.md
In Sentry 0.7, the crashpad backend became the default, so now we explicitly select the breakpad backend.
Using crashpad requires shipping the crash handler as an additional executable and it will take some investigation how that can work with an AppImage.
=> AppImage: Updated to Sentry 0.7.6

.github/workflows/packages.yml
The Sentry upload is optional.
Also, increase the log level to possibly find out why the upload appears to have failed with "error: Invalid checksum" last time.
=> CI: Don't fail a build if upload to Sentry failed

NEWS.md, docs/scripting-doc/index.d.ts, src/libtiled/object.cpp, src/libtiled/object.h, src/tiled/editableobject.cpp, src/tiled/editableobject.h, src/tiled/scriptmodule.cpp, src/tiled/scriptmodule.h
When setting a class value from a script, the value was not getting converted from a JS object to a QVariantMap. This tripped up code elsewhere, for example making the UI unable to edit the values (though it could still display them, and they also got saved correctly).
This change adds the missing conversion from JS object to QVariantMap to `tiled.propertyValue` and `Object.setProperty`.
=> Scripting: Fixed UI issues after setting class values

.github/workflows/packages.yml
Should be a relatively painless upgrade, though there was some [breakage with Qbs](https://bugreports.qt.io/browse/QTBUG-124903) in the 6.7.1 release regarding setting the minimum macOS version.
=> GitHub Actions: Updated builds to Qt 6.7.2

docs/reference/tmx-map-format.rst
Now they specify that their values should be at least 1, except in the case of image collection tilesets.
See https://github.com/mapeditor/rs-tiled/pull/292#pullrequestreview-2090246387.
=> docs: Be more specific about the tilewidth/height attributes

NEWS.md, src/tiled/editableobject.cpp
When the object reference was nested in a custom class, it was not getting converted between `EditableMapObject*` and `ObjectRef`.
=> Scripting: Fixed setting/getting nested object reference values

NEWS.md, src/tiled/automapperwrapper.cpp, tests/automapping/add-tileset/map-result.tmx, tests/automapping/add-tileset/map.tmx, tests/automapping/add-tileset/rules.tmx, tests/automapping/add-tileset/rules.txt
There was some code that should have done this, but it was checking which new tilesets were used before that actual changes had been applied, which entirely broke it. It was probably broken since Tiled 1.9.
=> Automapping: Fixed adding of new tilesets used by applied changes

.github/workflows/packages.yml
This appears to help with the "error: Invalid checksum" error encountered since Sentry Native 0.7.0.
=> Sentry: Upload only the .debug files and not all .o files

docs/manual/export-tscn.rst, docs/scripting-doc/index.d.ts
* Typo in export-tscn manual page
* \a doesn't work for referring to arguments in JS docs
=> docs: Some small fixes

src/tiled/document.cpp, src/tiledapp/main.cpp
It is useful to be able to load a project and its extensions when using the `--evaluate` parameter to execute a particular script.
Also fixed a crash in `Document` constructor when using the `--project` parameter, since it would generally cause a project to get loaded without there being a `DocumentManager`.
=> Allow --project to be used alongside the --evaluate CLI parameter

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/scriptfileformatwrappers.cpp, src/tiled/scriptfileformatwrappers.h
Exposes the file name filter used by a file format.
```
> tiled.mapFormat("tmx").nameFilter
$1 = Tiled map files (*.tmx *.xml)
> tiled.mapFormat("json").nameFilter
$2 = JSON map files (*.tmj *.json)
> tiled.mapFormat("lua").nameFilter
$3 = Lua files (*.lua)
```
=> Scripting: Added FileFormat.nameFilter

org.mapeditor.Tiled.appdata.xml
* Tiled requires a keyboard and a mouse to use.
* It supports tablet and touch input (or should, at least).
=> Added metadata about hardware support

src/tiled/mainwindow.cpp, src/tiled/tabbar.cpp, src/tiled/tiledapplication.cpp, src/tiled/tilesetdock.cpp
Also updated a bunch of comments using the old name for macOS.
=> Renamed usages of deprecated Q_OS_OSX define

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/mapeditor.cpp, src/tiled/mapeditor.h
So scripts can respond to brush changes. If they are careful, they can also adjust the brush, though this will trigger another `currentBrushChanged` call.
=> Scripting: Added MapEditor.currentBrushChanged signal

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/scriptmodule.cpp, src/tiled/scriptmodule.h
Can be used either to create one of the standard system cursors, or to create a custom cursor based on an image.
Created cursors can be set on custom tools and on widgets.
=> Scripting: Added tiled.cursor to create mouse cursor values

docs/scripting-doc/index.d.ts, src/tiled/scriptdialog.cpp, src/tiled/scriptdialog.h
In order to reduce the verbosity of the generated HTML, the parameter documentation is being left out, so these strings were not showing up anywhere. Where relevant they have been merged into the description.
See f954d3a47485a4e901c9a0df49d07f99f42a7db4.
=> docs: Don't use @param in scripting documentation

docs/scripting-doc/index.d.ts
Link to `Tileset.imageFileName` rather than the deprecated `Tileset.image`.
=> docs: Fixed link to deprecated property

src/plugins/python/python.qbs, tiled.qbs
I am Gentoo maintainer of Tiled. In Gentoo, there may be many Python versions installed at the same time for compatibility reasons, and each version has separate name in pkg-config.
For example, for Python 3.12 it would be named python-3.12-embed, so running pkg-config for python-embed will fail. Adding this option so it's possible to specify the correct name from build script.
=> Qbs: Add option to specify custom Python pkg-config name

docs/reference/support-for-tmx-maps.rst
Hello! Due to the amount of unmaintained and/or relatively old libraries in the .NET ecosystem for Tiled parsers, I've decided to make my own ([DotTiled](https://github.com/dcronqvist/DotTiled)) that I aim to maintain actively :)
Some of the ideas I want to accomplish with this library:
- fast and memory-efficient (see benchmark results for current status)
- easy to use and flexible API
- support for custom types with (in the future) automatic mapping between classes and Tiled custom types
- detailed usage documentation
- abstract renderer with ability to hook in relevant rendering backend
Please let me know if the description I've entered is too positively biased or should occur later in the list of mentioned libraries.
=> docs: Mention DotTiled library in C#/.NET section

NEWS.md, src/libtiled/world.cpp, src/libtiled/world.h, src/tiled/abstractworldtool.cpp, src/tiled/abstractworldtool.h, src/tiled/changeworld.cpp, src/tiled/changeworld.h, src/tiled/command.cpp, src/tiled/documentmanager.cpp, src/tiled/documentmanager.h, src/tiled/editablemap.cpp, src/tiled/editableworld.cpp, src/tiled/editableworld.h, src/tiled/mainwindow.cpp, src/tiled/mainwindow.h, src/tiled/mapdocument.h, src/tiled/mapitem.cpp, src/tiled/mapscene.cpp, src/tiled/projectdocument.h, src/tiled/scriptmodule.cpp, src/tiled/tilesetdocument.h, src/tiled/worlddocument.cpp, src/tiled/worlddocument.h, src/tiled/worldmanager.cpp, src/tiled/worldmanager.h, src/tiled/worldmovemaptool.cpp
This way it is more inline with how the other assets are managed. It also avoids silly issues, like a `WorldDocument` pointer not getting looked up successfully due to a file name mismatch.
Fixes #4042
=> Refactored World management

docs/reference/support-for-tmx-maps.rst
I was recently informed by the author and maintainer of [TiledCSPlus](https://github.com/krnlexception/TiledCSPlus) that they will no longer be maintaining the library, which was solidified by the repository being archived.
To reflect this in the Libraries and Frameworks section of the docs, it should be moved to the list of unmaintained (but probably still quite useful) libraries.
=> docs: Move TiledCSPlus to list of unmaintained C#/.NET libraries

NEWS.md, src/libtiled/world.cpp
Custom properties on worlds can only be accessed and modified through the scripting API at the moment, but since this is possible we better also save them.
Closes #4025
=> Implemented saving/loading of custom properties on worlds

docs/reference/json-map-format.rst, src/libtiled/maptovariantconverter.cpp
For consistency with the TMX format and other places where images are referenced (like tile images and tileset images).
Closes #4028
=> JSON format: Added image size for image layers

NEWS.md, src/tiled/tileanimationeditor.ui
0 is a valid value for the duration of an animation frame, so it should be possible to set the spinbox to 0 in order to apply this value to multiple selected frames at once.
=> Fixed minimum value of spinbox in Tile Animation Editor

snap/snapcraft.yaml
When this works, look into updating from Qt 5 to Qt 6 as well.
I went through https://snapcraft.io/docs/migrate-core24 but there didn't seem to be any relevant actions required.
=> snap: Migrate to core24

.github/workflows/docs.yml
Because it reported:
you may only define one of `paths` and `paths-ignore` for a single event
Unfortunately it had not said anything about that on the pull request, but apparently changes in paths are ignored for pull requests.
It's also quite annoying that this doesn't work...
=> GitHub Actions: Fixed workflow file

NEWS.md, src/tiled/tilesetdock.cpp, src/tiled/tilesetdock.h
The "current tile" was not being restored correctly after switching maps, when another type of object had been focused (for example due to switching layers or placing objects).
Now, when there is no "current tile" referenced by the `MapDocument`, it is set based on the tile selected in the current tileset view.
Closes #3497
Closes #3681
=> Fixed issue with placing tile objects after switching maps

NEWS.md, src/libtiled/maprenderer.cpp
Due to the tinting being applied to the entire tileset image, the 100 MB cache could easily be exhausted. This could result in the entire tileset image getting copied and tinted for each tile that is drawn.
Now only the relevant sub-rect is tinted and cached, which avoids doing needless tinting and has a much better performance even when the cache is not large enough.
=> Fixed performance issue when tinting tiles from large tilesets

.github/workflows/packages.yml, dist/win/installer.qbs
This release action does not allow renaming to be released files as part of releasing them, so now the original artifacts have been renamed to the desired final name, including the Tiled version and the compatible OS version.
=> CI: Migrate away from actions/create-release

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/editabletileset.cpp, src/tiled/editabletileset.h
Fix #3753 
Examples (scripting console with a Tileset as the active asset)
```
>tiled.activeAsset.transformationFlags |= Tileset.AllowFlipVertically
2
> tiled.activeAsset.transformationFlags
$8 = 2
> if ((tiled.activeAsset.transformationFlags | Tileset.AllowFlipVertically) > 0) { tiled.log('vertical flip enabled'); } 
vertical flip enabled
```
=> Scripting: Expose Tileset.transformationFlags

docs/scripting-doc/index.d.ts
While trying to publish to [jsr.io](https://jsr.io/), it reported:
error[syntax-error]: 'eval' and 'arguments' cannot be used as a binding identifier in strict mode
=> tiled-api: Fixed strict mode error

.gitignore, NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/mapeditor.cpp, src/tiled/mapeditor.h, src/tiled/tileseteditor.cpp, src/tiled/tileseteditor.h, src/tiled/wangcolormodel.cpp, src/tiled/wangdock.cpp, src/tiled/wangdock.h
Fix #4101
currentWangSet setter: seems to be working: 
```js
tiled.mapEditor.currentWangSet = tiled.activeAsset.tilesets[0].wangSets[0] 
```
~~Currently crashing,  I'm doing something wrong setting the currentWangColorIndex~~ Edit: working :
```
tiled.mapEditor.currentWangColorIndex  = 2 
```
I didn't see an existing public method to  change the selection so I tried to make one based on reading the rest of the code in wangdock.cpp . Maybe I missed something existing or just have  a logic error in my setter. Visually at least, it seems to change the color selection though. 
Causes crash: 
TODO (@dogboydog )
=> Scripting : Make MapEditor|TilesetEditor.currentWangSet and MapEditor|TilesetEditor.currentWangColorIndex writeable

NEWS.md, docs/scripting-doc/index.d.ts, src/tiled/scriptdialog.cpp, src/tiled/scriptdialog.h
Fix #3478 
TODO @dogboydog 
Examples: https://github.com/dogboydog/tiled-dialog-scripts Radio*.mjs
https://github.com/user-attachments/assets/175361e9-34ea-4f2e-ac0b-1296fecc9c64
=> Scripting: add addRadioButtonGroup to Dialog

.github/workflows/packages.yml
The `jurplel/install-qt-action` takes care of setting environment variables and caching.
=> CI: Use jurplel/install-qt-action instead of aqtinstall directly

.github/workflows/packages.yml
Seems like it does need Python set up. To avoid that breaking the Tiled compile, disable the Python plugin explicitly.
=> CI: Fixed installation of Qt on macOS

NEWS.md, src/tiled/mainwindow.cpp, src/tiled/projectmanager.cpp, src/tiled/projectmanager.h, src/tiled/tilestampmanager.cpp, src/tiled/tilestampmanager.h
The tilesets referenced by stored tile stamps may rely on custom types defined in the project and possibly even on custom tileset formats added by extensions. Hence, it is better to wait with loading them until after the project has been loaded and script manager is initialized.
The user will still run into issues when the project isn't loaded on startup, but this at least makes running into issues less likely.
It could help to force reloading of the stamps when switching projects.
=> Delay loading of tile stamps until after initializing the session

NEWS.md, src/tiled/automapper.cpp, src/tiled/automapper.h, tests/automapping/ignore-empty-region/map-result.tmx, tests/automapping/ignore-empty-region/map.tmx, tests/automapping/ignore-empty-region/rules.tmx, tests/automapping/ignore-empty-region/rules.txt, tests/automapping/test_automapping.cpp
Rules with an empty input region were causing issues, because they don't have a valid bounding rectangle. They are also commonly created by accident. If intended as a rule that always matches, such a rule can be made by placing the special "Ignore" tile in the rule's input.
Rules with empty output region are no longer matched because they would not produce any output anyway.
As a drive-by, `AutoMapper` no longer derives from `QObject`, which appears to have only been done to access the `tr()` function. This is now made available using `Q_DECLARE_TR_FUNCTIONS` instead.
Closes #3834
=> AutoMapping: Ignore rules with empty input or output regions

appveyor.yml
It was used as a condition for uploading releases to SignPath.
=> AppVeyor: Restored PUSH_RELEASE

src/tiled/changeproperties.cpp
* Set Property 'foo'
* Add Property 'foo'
* Remove Property 'foo'
Currently I haven't touched "Rename Property" because I think it would get a little too verbose if we mentioned two names. However, the name does mention the full path of a property if it is nested, separated by dots.
Also addressed a old occurrence of 'Type' which should have been renamed to 'Class' in Tiled 1.9.
=> Added property names to undo commands

NEWS.md, snap/snapcraft.yaml
Such that the Tiled snap will hopefully start working again on Wayland based on XWayland.
Currently we're seeing this when trying to launch Tiled on Wayland:
```
$ snap run tiled
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
qt.qpa.wayland: failed to create xkb context
QSocketNotifier: Can only be used with threads started with QThread
Segmentation fault (core dumped)
```
=> snap: Try to remove Wayland support

src/libtiled/object.cpp
By accident it was only returning the inherited properties. This was a regression in c99a1e77de2b41bad638b67272562f08e8289118.
=> Fixed Object::resolvedProperties

.github/workflows/packages.yml, appveyor.yml, snap/snapcraft.yaml
The `aseprite-msvc-dynamic-runtime.patch` is gone after its target `CMakeLists.txt` was merged into the qaseprite one in https://github.com/mapeditor/qaseprite/commit/180451b8ae1bc2d06abae22e099955ddf7b9ead6.
Check out the 1.0 tag to avoid future breakage in case changes are made to the plugin. Also use the new `update-submodules.sh` script to check out only the required submodules.
The snap has been updated as well to use the 1.0 source archive.
=> Fixed qaseprite compile on Windows

NEWS.md, docs/manual/export-yy.rst, src/plugins/yy/jsonwriter.cpp, src/plugins/yy/jsonwriter.h, src/plugins/yy/yyplugin.cpp
An update to GameMaker has broken compatibility in several ways:
* It now requires a "type tag field" at the start of applicable JSON records.
* The name is expected to follow the "type tag field" as a "%Name" field, in addition to the regular "name" field.
* The JSON fields are now required to be ordered alphabetically (case-insentively).
Other minor differences include:
* The "tags" field is left out when there are no tags.
* There is no longer a space included after JSON field names.
* Some new fields were added.
Also, the plugin now uses SaveFile again rather than QFile, because it seems that recent GameMaker versions will reload fine when using safe writing of files.
Closes #4132
=> YY plugin: Adjusted to changes in GameMaker file format

NEWS.md, docs/manual/layers.rst, docs/reference/json-map-format.rst, docs/reference/tmx-changelog.rst, docs/reference/tmx-map-format.rst, docs/scripting-doc/index.d.ts, src/libtiled/layer.cpp, src/libtiled/layer.h, src/libtiled/mapreader.cpp, src/libtiled/maptovariantconverter.cpp, src/libtiled/mapwriter.cpp, src/libtiled/minimaprenderer.cpp, src/libtiled/tiled.cpp, src/libtiled/tiled.h, src/libtiled/varianttomapconverter.cpp, src/plugins/lua/luaplugin.cpp, src/tiled/changeevents.h, src/tiled/changelayer.cpp, src/tiled/changelayer.h, src/tiled/editablelayer.cpp, src/tiled/editablelayer.h, src/tiled/imagelayeritem.cpp, src/tiled/mapitem.cpp, src/tiled/mapitem.h, src/tiled/mapobjectitem.cpp, src/tiled/propertieswidget.cpp, src/tiled/scriptmanager.cpp, src/tiled/tilelayeritem.cpp, src/tiled/undocommands.h, src/tmxrasterizer/tmxrasterizer.cpp
=> Added composition mode to layer

src/tiled/changeimagelayerproperty.h, src/tiled/changeobjectgroupproperties.h, src/tiled/propertieswidget.cpp, src/tiled/undocommands.h
Due to an inverted condition introduced in 629b53cea8dbc4ae46c9447a, it was not actually possible to change properties specific to image layers and object layers.
Also fixed the undo entry merging for these properties, which was broken because their undo commands did not have an ID.
=> Fixed ability to change image and object layer properties

src/libtiledquick/libtiledquick.qbs, src/tiledquick/main.cpp, src/tiledquick/qml/DragArea.qml, src/tiledquick/qml/FontAwesome.qml, src/tiledquick/qml/main.qml, src/tiledquick/tiledquick.qbs, src/tiledquickplugin/tiledquickplugin.qbs
* Migrated to new signal handling syntax.
* Removed version numbers from imports.
* Migrated to Settings from QtCore.
* Migrated to dialogs from QtQuick.Dialogs.
Some small other changes:
* Disable VSync since it makes things move erratically during resizing and delays response times.
* Round scaling factor since a fractional factor causes pixel movement during panning and window resizing.
=> Tiled Quick: Updated to require Qt 6.5

.github/workflows/packages.yml, appveyor.yml, dist/win/installer.qbs
Now qaseprite uses `qt_add_plugin`, which fixes the plugin's extension on macOS and unifies the file name to `qaseprite.dll` between MinGW and MSVC.
=> Github Actions: Try using latest qaseprite

NEWS.md, src/tiled/documentmanager.cpp
A crash could occur if a file (usually a map, tileset or world) got reloaded while no editor was currently open.
Thanks to crash reports sent to Sentry for exposing this one!
=> Fixed potential crash when handling file reloads

NEWS.md, src/tiled/propertieswidget.cpp
When there is more than one custom property selected when closing the last document, a crash would occur due to a null pointer dereference while updating the actions on the Properties view tool bar.
Thanks to crash reports sent to Sentry for exposing this one!
=> Fixed crash when closing last document with properties selected

NEWS.md, src/tiled/automapper.cpp
If an input index is entirely empty for a given rule, then this index will no longer cause the rule to always match.
An always-matching rule can still be declared by using the special "Ignore" tile in its input.
=> AutoMapping: Don't match rules based on empty input indexes

NEWS.md, src/tiled/automapper.cpp, src/tiled/automapper.h, src/tiled/automapperwrapper.cpp, src/tiled/automapperwrapper.h, src/tiled/automappingmanager.cpp, src/tiled/automappingmanager.h
By only deleting the `AutoMapper` instances for changed rule map files, the reloading becomes much faster since it can just reuse the still loaded instances.
Additionally, on-demand loading of rule maps avoids loading rule maps which do not apply to the current map based on file name filters.
Finally, re-parsing of the `rules.txt` file(s) now only happens when any of such files were changed, not when rule maps have changed.
=> AutoMapping: Optimized reloading of rule maps

.github/workflows/packages.yml
Switch from the deprecated "version" option to "release".
Added "fetch-depth: 0" to the checkout as suggested by the usage instructions for getsentry/action-release.
Replaces #4178.
=> GitHub Actions: Updated getsentry/action-release to v3

docs/reference/json-map-format.rst
The example was wrong since width 16 and height 16 implies 256 elements in data rather than 16
It also had trailing commas which made it invalid json
I also updated the description of width and height to be the same as for Layer.
=> docs: Fixed documentation for JSON Map Format - Chunk

.github/workflows/packages.yml
We can't use CMake 4 for now because of qaseprite not compiling due to some of its dependencies setting a CMake version below 3.5.
=> GitHub Actions: Pin cmake to 3.31

.github/workflows/packages.yml, src/karchive/karchive.qbs, src/libtiled/libtiled.qbs, src/libtiledquick/libtiledquick.qbs, src/plugins/python/python.qbs, src/qtsingleapplication/qtsingleapplication.qbs, src/tiled/libtilededitor.qbs, tiled.qbs
This fixes the following warning when using Qbs 2.6: "Resolving path properties relative to the exporting product's location is deprecated."
Raises the minimum version of Qbs to 1.18 (dropping support for compiling on Ubuntu 20.04 out of the box, which shipped with Qbs 1.13).
=> Qbs: Use exportingProduct.sourceDirectory

NEWS.md, src/tiled/tilesetview.cpp
It appears to be due to a bug in a recent memory usage optimization made to `QHeaderView` meant for very large models. This workaround effectively disables that optimization, but the tileset model generally isn't huge anyway.
Reported as [QTBUG-136453](https://bugreports.qt.io/browse/QTBUG-136453).
Closes #4191
=> Workaround tileset view layout regression in Qt 6.9

.github/workflows/packages.yml, docs/manual/python.rst
Support for Ubuntu 20.04 runner images will be dropped by 2025-04-15.
This also increases the Python version required by the Qt 5 AppImage from 3.8 to 3.10.
=> CI: Perform Qt 5 builds on Ubuntu 22.04

util/java/libtiled-java/pom.xml
dependency version updated from 2.3.3 -> 2.3.6
this change fixes the error that is thrown in java 21 when is called `new TMXMapReader()`
```
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
```
similar error occured in other projects
[https://github.com/highsource/jaxb-tools/issues/201#issuecomment-808009784](https://github.com/highsource/jaxb-tools/issues/201#issuecomment-808009784)
=> changed org.glassfish.jaxb dependency version

src/tiled/variantmapproperty.cpp
Failing to return false here would lead to invalid index in caller.
Split off from #4002 since this crash fix is relevant when switching between that branch and master.
=> Fixed potential crash if property creation fails for whatever reason

NEWS.md, src/tiled/abstracttileselectiontool.cpp, src/tiled/resources/images/scalable/fill-full-tiles.svg, src/tiled/wangbrush.cpp, src/tiled/wangbrush.h
Hi, I have tried to address https://github.com/mapeditor/tiled/issues/3082. I hope it is useful.
A few things I wasn't sure about:
- I don't really understand the translations so I didn't add any for the new text I added.
- I didn't make an icon for the new toolbar tool I added; I just re-used an icon fromsomething else. But it's not really appropriate, so I need some guidance about which icon to pick.
=> Make Terrain Brush fill full tiles mode toggle-able

src/tiled/propertieswidget.cpp
Due to a missing parent on the `GroupProperty` used by the `PropertiesWidget`, the `GroupProperty` instance would not get deleted, which in turns causes the `CustomProperties` instance to not get deleted.
The leaked `CustomProperties` instance would later cause a crash when editing the custom types because it accesses a roaming Document pointer while it tries to update itself.
=> Fixed possible crash in the Custom Types Editor

NEWS.md, docs/manual/editing-tile-layers.rst, src/tiled/tileselectiontool.cpp, src/tiled/tileselectiontool.h
Now while selecting with the Rectangular Select tool, holding Shift will constrain the selection to a square shape, and holding Ctrl (Cmd on macOS) will expand the selection from its center.
Part of issue #4201
=> Add square selection and expand-from-center to Rectangular Select tool

NEWS.md, src/tiled/stampbrush.cpp, src/tiled/stampbrush.h
Now displays some additional information when capturing or drawing lines
or ellipses:
* When capturing a stamp: "Capture area (\<width> x \<height>)"
* When drawing an ellipse: "Draw ellipse (size: \<width> x \<height>)"
* When drawing a line: "Draw line (length: \<length>)"
Closes #3092
See also issue #4201
=> Expand the status bar info for the Stamp Brush

.gitignore
I added a local symlink here to the `compile_commands.json` file generated at `defaults/compile_commands.json`, which helps `clangd` understand the code. The linked file can be generated using:
qbs generate -g clangdb
=> Added compile_commands.json to .gitignore

src/tiled/propertiesview.cpp
Small regression in b081934a7fa12c2df0fc0213d59de3200d030896 caused the mouse wheel to affect the value of unfocused spin boxes again.
=> Fixed wheel behavior on spin boxes in Properties view
